-- Mickey's Not-So-Scary Halloween Party (MNSSHP) 2026: 7 new Kiosk booths
-- and 59 Snack & Sip items at Magic Kingdom, mirroring the EPCOT Food & Wine
-- kiosk/booth pattern (category 'kiosk' for booths, category 'snack' with
-- booth_id for items, seasonal jsonb for the date range).
--
-- Ticket gating: unlike Food & Wine, MNSSHP is a separate hard-ticket event,
-- so seasonal carries ticket_required: true. The source spreadsheet notes
-- that the party only runs select nights within Aug 7 - Oct 31 (not every
-- night) -- that finer-grained party calendar isn't captured here; seasonal
-- start/end mark the outer season only, same limitation as the F&W booths.
--
-- Party Only / Day & Party / Day Only availability (MNSSHP has all three,
-- where F&W items are always festival-only) is stored as a tags entry
-- alongside 'New 2026' and 'Plant-based', following the existing
-- free-form-tags convention rather than adding a dedicated column.
--
-- Closing times ("Party Closes At" in the source) are folded into the
-- Kiosk booth description text rather than a new schema column, matching
-- how F&W booth hours/logistics live in prose today.
--
-- 12 of the 19 locations already existed in the catalog (regular MK dining/
-- snack rows) and are merged into their existing ids via booth_id rather
-- than duplicated -- same pattern as the regular snacks catalog import.
-- Only the 7 missing locations (Plaza Ice Cream Parlor, Auntie Gravity's,
-- Cheshire Cafe, Storybook Treats, Friar's Nook, Liberty Square Market,
-- Aloha Isle Refreshments) get new kiosk-mn-* rows.
--
-- Prices came from a follow-up version of the source spreadsheet with a
-- Price column added; price_label is formatted '~$X.XX' to match the
-- existing snack catalog convention. The Be Our Guest and Cinderella's
-- Royal Table party items share one flat per-person price across their
-- multiple courses/drinks (a prix-fixe menu), not per-item pricing --
-- that's the real structure of those party menus, not a data error.
--
-- Queen of Hearts Tart is Day Only at Cheshire Cafe and Party Only at
-- Storybook Treats -- same item name, two different locations/states, so
-- the Storybook Treats row gets a disambiguated id.
insert into catalog_items (id, name, park, category, description, price_label, price_mid, location_detail, dining_tier, cuisine, dining_plan_credits, seasonal, tags, booth_id, item_type) values
  ('kiosk-mn-plaza-ice-cream-parlor', 'Plaza Ice Cream Parlor', 'MK', 'kiosk', 'Pumpkin gelato sundae available during regular park hours and party nights. Closes at 11 PM.', null, null, 'Main Street, U.S.A.', null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, null, null, null),
  ('kiosk-mn-auntie-gravitys-galactic-goodies', 'Auntie Gravity''s Galactic Goodies', 'MK', 'kiosk', 'Candy Bowl Sundae (party only) and Cauldron Cold Brew (day and party). Closes at 11 PM.', null, null, 'Tomorrowland', null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, null, null, null),
  ('kiosk-mn-cheshire-cafe', 'Cheshire Cafe', 'MK', 'kiosk', 'Queen of Hearts Tart is a DAYTIME item here — not available on party nights at this location. Grab it during the day if you''re entering early.', null, null, 'Fantasyland', null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, null, null, null),
  ('kiosk-mn-storybook-treats', 'Storybook Treats', 'MK', 'kiosk', 'Queen of Hearts Tart (party-only here) and the beloved Ursula Cone. Closes at 10 PM. Note: the same Queen of Hearts Tart is a day item at Cheshire Cafe.', null, null, 'Fantasyland', null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, null, null, null),
  ('kiosk-mn-friars-nook', 'Friar''s Nook', 'MK', 'kiosk', 'Four party-exclusive savory and sweet items. The Buffalo Chicken Hand Pie consistently draws a line. Strong single stop if you want savory in Fantasyland without a reservation. Closes at Midnight during the party.', null, null, 'Fantasyland', null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, null, null, null),
  ('kiosk-mn-liberty-square-market', 'Liberty Square Market', 'MK', 'kiosk', 'Closes at 8:30 PM — the earliest closure of any MNSSHP food location. Magic Potion Slushy is available both day and party. Get here early in the party night.', null, null, 'Liberty Square', null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, null, null, null),
  ('kiosk-mn-aloha-isle-refreshments', 'Aloha Isle Refreshments', 'MK', 'kiosk', 'DOLE Whip Mango and Chamoy Float available during regular park hours and party nights. A refreshing, kid-friendly option in Adventureland.', null, null, 'Adventureland', null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, null, null, null),
  ('mn-chipotle-bbq-pork-and-street-corn-french-fries', 'Chipotle BBQ Pork & Street Corn French Fries', 'MK', 'snack', 'French fries topped with fire-roasted corn, queso fresco, jalapeño ranch, and cilantro. A savory party staple.', '~$7.99', 7.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-casey-s-corner', 'food'),
  ('mn-chipotle-bbq-pork-and-street-corn-hot-dog', 'Chipotle BBQ Pork & Street Corn Hot Dog', 'MK', 'snack', 'All-beef hot dog with the same fire-roasted street corn topping as the fries. The street corn treatment has been a Casey''s party signature for several years.', '~$14.99', 14.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-casey-s-corner', 'food'),
  ('mn-chipotle-bbq-pork-and-street-corn-mini-corn-dogs', 'Chipotle BBQ Pork & Street Corn Mini Corn Dogs', 'MK', 'snack', 'Mini corn dogs with fire-roasted corn, queso fresco, jalapeño ranch, and cilantro. One of Disney''s recommended ''best for kids'' items at the party. Great for sharing.', '~$10.99', 10.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-casey-s-corner', 'food'),
  ('mn-headless-horseman-treat', 'Headless Horseman Treat', 'MK', 'snack', 'Pumpkin pie tart with whipped cheesecake, spiced caramel panna cotta, candied pecans, and marshmallow buttercream ''flames.'' New for 2026 — possibly the most photogenic item of the party.', '~$6.99', 6.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 's-casey-s-corner', 'food'),
  ('mn-mickey-cinnamon-roll', 'Mickey Cinnamon Roll', 'MK', 'snack', 'Classic Mickey-shaped cinnamon roll with white icing and Halloween sprinkles. A reliable, crowd-pleasing sweet treat that works for any age.', '~$7.99', 7.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-main-street-bakery', 'food'),
  ('mn-mickey-shaped-pumpkin-cheesecake', 'Mickey-shaped Pumpkin Cheesecake', 'MK', 'snack', 'Mickey-shaped pumpkin cheesecake on a graham cracker crust with white chocolate whipped ganache. Party-exclusive and best grabbed on the way in or out.', '~$6.49', 6.49, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-main-street-bakery', 'food'),
  ('mn-pumpkin-sundae', 'Pumpkin Sundae', 'MK', 'snack', 'Pumpkin gelato with pumpkin-spiced caramel sauce, pumpkin brittle, and Halloween sprinkles. Available during regular park hours — no party ticket required for this one.', '~$8.29', 8.29, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day & Party']::text[], 'kiosk-mn-plaza-ice-cream-parlor', 'food'),
  ('mn-devilish-crispy-chicken-sandwich', 'Devilish Crispy Chicken Sandwich', 'MK', 'snack', 'Fried chicken breast with ghoulish spiced mayonnaise, red cabbage, and Fresno peppers on a black kaiser roll, served with french fries. New for 2026. Available day and party — table service reservation recommended.', '~$26.00', 26.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day & Party','New 2026']::text[], 'd-the-plaza-restaurant', 'food'),
  ('mn-skull-meatloaf', 'Skull Meatloaf', 'MK', 'snack', 'Caribbean-style glazed meatloaf served with loaded mashed potatoes and seasonal vegetables. Available day and party. One of the few savory options accessible without a party ticket.', '~$27.00', 27.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day & Party']::text[], 'd-the-plaza-restaurant', 'food'),
  ('mn-phantom-pecan-caramel-cheesecake', 'Phantom Pecan-Caramel Cheesecake', 'MK', 'snack', 'Layers of New York and caramel cheesecake with dulce de leche, chocolate ganache, and pecans on a chocolate crust. New for 2026. Available day and party.', '~$10.00', 10.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day & Party','New 2026']::text[], 'd-the-plaza-restaurant', 'food'),
  ('mn-goblins-and-ghoulies', 'Goblins and Ghoulies', 'MK', 'snack', 'Captain Morgan Original Spiced Rum, Disaronno Originale Liqueur, apple cider, and pomegranate juice. One of the few alcoholic cocktails available to day guests during Halloween season.', '~$17.50', 17.5, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day & Party']::text[], 'd-the-plaza-restaurant', 'drink'),
  ('mn-candy-bowl-sundae', 'Candy Bowl Sundae', 'MK', 'snack', 'Vanilla soft-serve with chocolate cone dip, SNICKERS, TWIX, and M&M''s Halloween Blend. A candy-lover''s dream sundae — party-exclusive.', '~$7.99', 7.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'kiosk-mn-auntie-gravitys-galactic-goodies', 'food'),
  ('mn-cauldron-cold-brew', 'Cauldron Cold Brew', 'MK', 'snack', 'Joffrey''s Cold Brew Coffee with pumpkin-spiced foam and Halloween sprinkles. Non-alcoholic. Available during regular park hours — no ticket required.', '~$6.49', 6.49, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day & Party']::text[], 'kiosk-mn-auntie-gravitys-galactic-goodies', 'drink'),
  ('mn-creepy-kimchi-hot-dog', 'Creepy Kimchi Hot Dog', 'MK', 'snack', 'Sriracha cream cheese, kimchi, and Hades relish. A fun, bold flavor combo. Closes at 10 PM — prioritize early in the party.', '~$13.99', 13.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-the-lunching-pad', 'food'),
  ('mn-jalape-o-popper-hot-dog', 'Jalapeño Popper Hot Dog', 'MK', 'snack', 'Queso fundido, pickled and fried jalapeños, bacon, and onions. Party-exclusive and closes at 10 PM.', '~$14.99', 14.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-the-lunching-pad', 'food'),
  ('mn-hades-cake-pop', 'Hades Cake Pop', 'MK', 'snack', 'Mexican hot chocolate cake with popping candies, dipped in chocolate with blue marshmallow ''fire.'' New for 2026 and one of the most theatrical-looking items at the party. Closes at 10 PM.', '~$6.29', 6.29, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 's-the-lunching-pad', 'food'),
  ('mn-ghoulish-blue-raspberry-slushy', 'Ghoulish Blue Raspberry Slushy', 'MK', 'snack', 'Fanta Blue Raspberry Slushy with black vanilla drizzle. Non-alcoholic. Available during regular park hours — a kid-friendly option.', '~$6.79', 6.79, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day & Party']::text[], 's-the-lunching-pad', 'drink'),
  ('mn-fang-tastic-garlic-butter-burger', 'Fang-tastic Garlic Butter Burger', 'MK', 'snack', 'Angus beef with Boursin and brie fondue, crispy onions, and garlic pickles on a toasted black bun, served with french fries. New for 2026 — the black bun is very on-theme.', '~$14.99', 14.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 's-cosmic-ray-s-starlight-cafe', 'food'),
  ('mn-sweet-and-spicy-chicken-strips', 'Sweet-and-Spicy Chicken Strips', 'MK', 'snack', 'Korean barbecue sauce with black sesame seeds, crispy garlic, and green onions, served with french fries. Party-exclusive.', '~$12.99', 12.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-cosmic-ray-s-starlight-cafe', 'food'),
  ('mn-minnie-witch-hat', 'Minnie Witch Hat', 'MK', 'snack', 'Sugar cookie topped with strawberry-banana mousse, chocolate, and buttercream. A returning fan favorite — the 2026 version is updated from 2025''s peanut butter mousse base.', '~$7.99', 7.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-cosmic-ray-s-starlight-cafe', 'food'),
  ('mn-oogie-boogie-slushy', 'Oogie Boogie Slushy', 'MK', 'snack', 'Frozen apple cider with cinnamon whipped cream and sour gummy candy. Non-alcoholic. Party-exclusive.', '~$6.99', 6.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-cosmic-ray-s-starlight-cafe', 'drink'),
  ('mn-queen-of-hearts-tart', 'Queen of Hearts Tart', 'MK', 'snack', 'Sour cherry pie filling tart. DAYTIME item only at this location — not available on party nights here. New for 2026. The same item is party-only at Storybook Treats.', '~$5.79', 5.79, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day Only','New 2026']::text[], 'kiosk-mn-cheshire-cafe', 'food'),
  ('mn-queen-of-hearts-tart-storybook-treats', 'Queen of Hearts Tart', 'MK', 'snack', 'Sour cherry pie filling tart. PARTY-ONLY at this location. The same item is available during the day at Cheshire Cafe. New for 2026. Storybook Treats closes at 10 PM.', '~$5.79', 5.79, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 'kiosk-mn-storybook-treats', 'food'),
  ('mn-ursula-cone', 'Ursula Cone', 'MK', 'snack', 'Wild berry soft-serve with candy coral and citrus cotton candy in a black vanilla cone. A returning fan favorite that consistently draws a crowd. Closes at 10 PM — go early.', '~$8.49', 8.49, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'kiosk-mn-storybook-treats', 'food'),
  ('mn-bowl-of-bones', 'Bowl of Bones', 'MK', 'snack', 'Pork wings fried with jalapeños and tossed in barbecue sauce made with Coca-Cola Cherry. Savory and a bit spicy — a strong choice if you want something substantial.', '~$13.99', 13.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'kiosk-mn-friars-nook', 'food'),
  ('mn-buffalo-chicken-hand-pie', 'Buffalo Chicken Hand Pie', 'MK', 'snack', 'Buffalo chicken and mozzarella in flaky dough with blue cheese crumbles and Buffalo-ranch. One of the most popular items at MNSSHP — expect a line after 8 PM. Open until midnight.', '~$9.99', 9.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'kiosk-mn-friars-nook', 'food'),
  ('mn-haunting-jalape-o-tots', 'Haunting Jalapeño Tots', 'MK', 'snack', 'Tots with plant-based black bean chili, cheddar sauce, and jalapeño sauce. One of the few plant-based savory options at the party.', '~$10.49', 10.49, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','Plant-based']::text[], 'kiosk-mn-friars-nook', 'food'),
  ('mn-not-so-poison-apple-doughnuts', 'Not-So-Poison Apple Doughnuts', 'MK', 'snack', 'Doughnuts rolled in apple cider sugar and drizzled with caramel sauce. A returning crowd-pleaser and one of Disney''s recommended ''best for kids'' items. Open until midnight.', '~$6.49', 6.49, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'kiosk-mn-friars-nook', 'food'),
  ('mn-fra-diavolo-chicken-sandwich', 'Fra Diavolo Chicken Sandwich', 'MK', 'snack', 'Fried chicken breast with fra diavolo sauce, cheese, basil pesto, and arugula on a ciabatta bun, served with french fries. New for 2026. Closes at 10 PM — plan accordingly.', '~$13.99', 13.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 's-pinocchio-village-haus', 'food'),
  ('mn-phantasmal-fried-pumpkin-ravioli', 'Phantasmal Fried Pumpkin Ravioli', 'MK', 'snack', 'Fried pumpkin ravioli served with black garlic aïoli and a side Caesar salad. A returning favorite — one of the most distinctive savory items at MNSSHP. Closes at 10 PM.', '~$11.49', 11.49, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-pinocchio-village-haus', 'food'),
  ('mn-undead-garlic-parmesan-chicken-strips', 'Undead Garlic-Parmesan Chicken Strips', 'MK', 'snack', 'Garlic-Parmesan sauce and parsley, served with french fries. Party-exclusive. Closes at 10 PM.', '~$12.99', 12.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-pinocchio-village-haus', 'food'),
  ('mn-cruella-cookie-sandwich', 'Cruella Cookie Sandwich', 'MK', 'snack', 'Chocolate cookies filled with raspberry ganache, dipped in white chocolate and sprinkles. New for 2026. A very photogenic dessert. Closes at 10 PM.', '~$7.99', 7.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 's-pinocchio-village-haus', 'food'),
  ('mn-scary-ghost-slushy', 'Scary Ghost Slushy', 'MK', 'snack', 'Blue raspberry slushy with marshmallow foam and a marshmallow ghost. Non-alcoholic. One of Disney''s recommended ''best for kids'' items. Closes at 10 PM.', '~$6.79', 6.79, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-pinocchio-village-haus', 'drink'),
  ('mn-beef-short-rib', 'Beef Short Rib', 'MK', 'snack', 'Slowly cooked in cabernet sauvignon and figs with butternut squash purée and roasted fall vegetables. New for 2026. Party-exclusive table service — reservations required starting at 4 PM.', '~$72.00', 72.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 'd-bog', 'food'),
  ('mn-the-forbidden-rose', 'The Forbidden Rose', 'MK', 'snack', '''The Grey Stuff,'' black buttercream, and a black rose petal. A beloved Be Our Guest party dessert. Reservations required.', '~$72.00', 72.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'd-bog', 'food'),
  ('mn-apple-cider-margarita', 'Apple Cider Margarita', 'MK', 'snack', 'Teremana Blanco Tequila, Grand Marnier Liqueur, and apple cider. New for 2026. One of the few cocktails available inside Magic Kingdom (alcohol is limited to select TS restaurants).', '~$18.00', 18.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 'd-bog', 'drink'),
  ('mn-castle-fog', 'Castle Fog', 'MK', 'snack', 'Empress 1908 Gin, Bols Blackberry Liqueur, lemon juice, and cane syrup. A stunning purple cocktail — the gin turns lavender on contact with the blackberry.', '~$18.00', 18.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'd-bog', 'drink'),
  ('mn-chicken-cauldron', 'Chicken Cauldron', 'MK', 'snack', 'Black truffle sauce, root vegetables, and potato-pumpkin purée. New for 2026. Party-exclusive table service starting at 4 PM — the hardest reservation to get at MNSSHP.', '~$88.00', 88.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 'd-crt', 'food'),
  ('mn-beef-short-rib-en-cro-te', 'Beef Short Rib en Croûte', 'MK', 'snack', 'Fall vegetables and roasted beet demi-glace. A returning party special at Cinderella''s Royal Table. Reservations required.', '~$88.00', 88.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'd-crt', 'food'),
  ('mn-supernatural-shrimp', 'Supernatural Shrimp', 'MK', 'snack', 'Avocado mousse, tomato horseradish sauce, rice cracker, and wasabi peas. A light seafood starter — party-exclusive at Cinderella''s Royal Table.', '~$88.00', 88.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'd-crt', 'food'),
  ('mn-creepy-cheesecake', 'Creepy Cheesecake', 'MK', 'snack', 'Pumpkin cheesecake with spiced oranges, orange curd, and chocolate crumbs. A consistently strong dessert offering at the party.', '~$88.00', 88.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'd-crt', 'food'),
  ('mn-pumpkin-spice-margarita', 'Pumpkin Spice Margarita', 'MK', 'snack', 'Lalo Blanco Tequila, RumChata Cream Liqueur, pumpkin spice syrup, and oat milk with crushed cinnamon-sugar graham crackers. A uniquely autumnal party cocktail.', '~$19.00', 19.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'd-crt', 'drink'),
  ('mn-violet-specter', 'Violet Specter', 'MK', 'snack', 'Tito''s Handmade Vodka, Chambord Liqueur, lemon juice, and Sprite, garnished with mint and a Luxardo cherry. A fruit-forward party cocktail at Cinderella''s Royal Table.', '~$19.00', 19.0, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 'd-crt', 'drink'),
  ('mn-doom-buggy-dumplings', 'Doom Buggy Dumplings', 'MK', 'snack', 'Chicken dumplings with red miso gochujang sauce, furikake, and chili threads. New for 2026 — one of the most buzzed-about new items of the party. Haunted Mansion theming is a clever touch.', '~$8.99', 8.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 's-sleepy-hollow', 'food'),
  ('mn-graveyard-hot-chicken-and-waffle', 'Graveyard Hot Chicken and Waffle', 'MK', 'snack', 'Nashville hot chicken strips on a blue cornmeal waffle with pickle ranch. New for 2026. Sleepy Hollow is known for its waffle sandwiches year-round — this is the Halloween upgrade.', '~$13.29', 13.29, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 's-sleepy-hollow', 'food'),
  ('mn-hatbox-ghost-pop', 'Hatbox Ghost Pop', 'MK', 'snack', 'Chocolate crumbs layered with chocolate mousse and dulce de leche, topped with blue crispy pearls and a chocolate piece. New for 2026. The Hatbox Ghost is one of the Haunted Mansion''s most beloved characters.', '~$6.29', 6.29, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 's-sleepy-hollow', 'food'),
  ('mn-pumpkin-spiced-funnel-cake-sundae', 'Pumpkin-spiced Funnel Cake Sundae', 'MK', 'snack', 'Pumpkin funnel cake with pumpkin gelato, whipped cream, pumpkin-spiced caramel, candy pumpkins, and sprinkles. A returning Sleepy Hollow party classic.', '~$8.99', 8.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-sleepy-hollow', 'food'),
  ('mn-smores-cup', 'S''mores Cup', 'MK', 'snack', 'Layers of graham cracker pieces, chocolate ganache, popping chocolate candies, milk chocolate panna cotta, and marshmallow cream. DAYTIME item only — NOT available on party nights. Grab it during regular hours.', '~$5.99', 5.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day Only']::text[], 's-columbia-harbour-house', 'food'),
  ('mn-magic-potion-slushy', 'Magic Potion Slushy', 'MK', 'snack', 'Fanta Blue Raspberry slushy with yuzu — shifts from blue to green as you stir. Non-alcoholic. Available day and party. Note: Liberty Square Market closes at 8:30 PM during the party — the earliest of any location.', '~$6.59', 6.59, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day & Party']::text[], 'kiosk-mn-liberty-square-market', 'drink'),
  ('mn-cursed-cowboy-fries', 'Cursed Cowboy Fries', 'MK', 'snack', 'Sweet potato fries with barbecue burnt ends, chipotle queso, pico de gallo, and crispy jalapeños. New for 2026. Closes at 10 PM.', '~$10.49', 10.49, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 's-pecos-bill-tall-tale-inn-and', 'food'),
  ('mn-frightful-black-bean-burger', 'Frightful Black Bean Burger', 'MK', 'snack', 'Plant-based patty with jalapeño-ranch slaw and jalapeño chips, served with french fries. New for 2026. One of the best plant-based options at the party. Closes at 10 PM.', '~$12.99', 12.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026','Plant-based']::text[], 's-pecos-bill-tall-tale-inn-and', 'food'),
  ('mn-buzzard-wings', 'Buzzard Wings', 'MK', 'snack', 'Whole chicken wings tossed with grilled onions, jalapeños, and lime. A spicy, shareable option. Closes at 10 PM.', '~$11.99', 11.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-pecos-bill-tall-tale-inn-and', 'food'),
  ('mn-skull-icious-cake', 'Skull-icious Cake', 'MK', 'snack', 'Chocolate cake, chocolate mousse, and peanut butter buttercream with chocolate popping candies on a chocolate cookie crust. New for 2026. Closes at 10 PM.', '~$6.29', 6.29, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only','New 2026']::text[], 's-pecos-bill-tall-tale-inn-and', 'food'),
  ('mn-pumpkin-patch-mini-churros', 'Pumpkin Patch Mini Churros', 'MK', 'snack', 'Rolled in orange sugar and served with pumpkin cheesecake dip. A kid-friendly sweet snack. Closes at 10 PM.', '~$6.99', 6.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-pecos-bill-tall-tale-inn-and', 'food'),
  ('mn-guava-lemonade-slushy', 'Guava Lemonade Slushy', 'MK', 'snack', 'Guava lemonade slushy with cheesecake foam, Halloween sprinkles, and a sugar spider. Non-alcoholic. Closes at 10 PM.', '~$6.79', 6.79, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-pecos-bill-tall-tale-inn-and', 'drink'),
  ('mn-cajun-crawfish-and-sausage-bootine', 'Cajun Crawfish and Sausage BOOtine', 'MK', 'snack', 'Waffle fries topped with cheese curds and Cajun crawfish-andouille sausage gravy. A New Orleans-inspired indulgence. Open until midnight.', '~$12.99', 12.99, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-golden-oak-outpost', 'food'),
  ('mn-beignets-from-beyond', 'Beignets from Beyond', 'MK', 'snack', 'Beignets with powdered sugar and chocolate cookie pieces over cookies and cream cheese icing. One of Disney''s recommended ''best for kids'' items. Open until midnight.', '~$8.79', 8.79, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-golden-oak-outpost', 'food'),
  ('mn-hot-honey-lemonade', 'Hot Honey Lemonade', 'MK', 'snack', 'Minute Maid Premium Lemonade with hot honey and a chili-lime rim. Non-alcoholic. A refreshing sweet-heat combination. Open until midnight.', '~$6.29', 6.29, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Party Only']::text[], 's-golden-oak-outpost', 'drink'),
  ('mn-dole-whip-mango-and-chamoy-float', 'DOLE Whip Mango and Chamoy Float', 'MK', 'snack', 'DOLE Whip Mango with DOLE Pineapple Juice, chamoy, and chili-lime seasoning. Available during regular park hours and party nights. A tangy tropical twist on the classic DOLE Whip float.', '~$7.49', 7.49, null, null, null, null, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Day & Party']::text[], 'kiosk-mn-aloha-isle-refreshments', 'food')
on conflict (id) do update set name=excluded.name, park=excluded.park, category=excluded.category, description=excluded.description, price_label=excluded.price_label, price_mid=excluded.price_mid, location_detail=excluded.location_detail, dining_tier=excluded.dining_tier, cuisine=excluded.cuisine, dining_plan_credits=excluded.dining_plan_credits, seasonal=excluded.seasonal, tags=excluded.tags, booth_id=excluded.booth_id, item_type=excluded.item_type;
