-- Replaces the 19-item Experiences catalog from the previous import with
-- the full 79-item list from Disney's official Enchanting Extras
-- Collection (tours, recreation, dining packages, dessert parties,
-- spas, golf, and more). The source spreadsheet's Events tab is
-- unchanged from the prior import.
--
-- Disney's own "Enchanting Extras" grouping (Unique Tours, Special
-- Occasions, Adventures in Dining, Spectacular Sweet Spots, Make Believe
-- & More, Rest & Recreation) is stored as a tag alongside the existing
-- event_type tag (Select Nights / Year-Round / Season) and one-off flags
-- (Per Group, Per Hour, Adults Only, No Park Admission Required) -- same
-- free-form-tags convention as before, no new column.
--
-- 5 rows from the prior import were renamed or restructured in this
-- version and are deleted before the fresh insert so they don't linger
-- as orphaned duplicates: Keys to the Kingdom Tour and the VIP Tour both
-- picked up a fuller name, Savi's Workshop and Droid Depot both gained a
-- "Star Wars: Galaxy's Edge" prefix, and the single Tomorrowland Terrace
-- dessert party split into three separate packages (Pre-Party,
-- Post-Party, Seats & Sweets). Everything else keeps its existing id and
-- upserts in place (price/description refreshes only).
--
-- Seasonal linking grew from 4 to 8 rows tied to an existing festival
-- window (MNSSHP, MVMCP, Food & Wine, Festival of the Arts, Flower &
-- Garden, Festival of the Holidays, Jollywood Nights) -- the new Eat to
-- the Beat / Disney on Broadway / Garden Rocks concert dining packages
-- and the Jollywood-exclusive Jazzy Holidays lounge all reuse the same
-- seasonal.festival strings as their underlying event/food catalog rows.
--
-- Blizzard Beach had no park code in the app (Typhoon Lagoon was added in
-- the prior migration) -- added 'BB' alongside it in the same commit.
-- 'Resort (Various)', 'Multiple Parks', and 'EPCOT Resort Area' locations
-- reuse the existing 'All parks' wildcard sentinel since they aren't tied
-- to one specific park or resort.
-- Stale ids from the v1/v2 Experiences import, superseded by a renamed or
-- restructured row below (see migration header).
delete from catalog_items where id in (
  'ex-keys-to-the-kingdom-tour',
  'ex-vip-tour-private-theme-park-experience',
  'ex-savis-workshop-handbuilt-lightsabers',
  'ex-star-wars-droid-depot',
  'ex-enchanting-extras-fireworks-dessert-party-tomorrowland-terrace'
);

insert into catalog_items (id, name, park, category, description, price_label, price_mid, seasonal, tags) values
  ('ex-wild-africa-trek', 'Wild Africa Trek', 'AK', 'experience', 'A 3-hour guided trek through backstage Kilimanjaro Safaris, crossing rope bridges above hippo and crocodile pools, spending time at a private savanna overlook, and enjoying an African-inspired catered snack stop. Maximum 12 guests per group. Harness and safety gear provided. One of the most physically immersive experiences at Walt Disney World. Requires park admission. Note: Multiple departures daily — book well in advance; min. age 8; max. weight 310 lbs.', '$229–$239 + tax (varies by date)', 234.0, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-savor-the-savanna', 'Savor the Savanna', 'AK', 'experience', 'An evening private safari excursion through the Harambe Wildlife Preserve with an expert guide, followed by a curated spread of African-inspired tapas, cocktails, and non-alcoholic beverages at a private overlook platform with savanna views. A more intimate and relaxed alternative to the Wild Africa Trek. Requires park admission. Note: Select evenings — reservations required.', '$199–$209 + tax (varies by date)', 204.0, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-caring-for-giants', 'Caring for Giants', 'AK', 'experience', 'A guided walking experience through the elephant habitat at Animal Kingdom, learning about the park''s herd from the animal care team. Guests observe feeding and enrichment activities up close from a dedicated viewing area. One of the most touching Animal Kingdom experiences for wildlife enthusiasts. Requires park admission. Note: Select mornings — reservations required; minimum age 4.', 'Starting from $39 + tax', 39.0, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-up-close-with-rhinos', 'Up Close with Rhinos', 'AK', 'experience', 'A guided backstage encounter with Animal Kingdom''s white rhinoceroses, led by the animal care team. Guests learn about rhino conservation and animal behavior from a special private viewing area. A rare opportunity to get within a short distance of these impressive animals. Requires park admission. Note: Select mornings — reservations required; minimum age 4.', 'Starting from $49 + tax', 49.0, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-epcot-seas-adventures-divequest', 'EPCOT Seas Adventures – DiveQuest', 'EPCOT', 'experience', 'A 3-hour guided scuba experience inside The Seas with Nemo & Friends aquarium — one of the largest inland saltwater aquariums in the world. Dive with sharks, rays, sea turtles, and thousands of fish in crystal-clear water with guaranteed visibility. Tank equipment provided; certification required. Requires park admission — and earns serious bragging rights. Note: Select days; minimum age 10; scuba certification required.', '$229–$249 + tax (varies by date)', 239.0, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-behind-the-seeds', 'Behind the Seeds', 'EPCOT', 'experience', 'A guided backstage walking tour of the four greenhouse labs and fish farm beneath the Living with the Land attraction. Guests see experimental growing techniques including plants grown in nutrient-rich water without soil, fish farming operations, and Disney''s actual food production for the parks. A fascinating deep dive for curious minds of all ages. Requires park admission. Note: Multiple times daily — walk-in or advance booking available.', '$39–$49 + tax (varies by date)', 44.0, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-starlight-safari-at-animal-kingdom-lodge', 'Starlight Safari at Animal Kingdom Lodge', 'AKL', 'experience', 'An after-dark guided safari walk through the Jambo House savanna reserve using night vision equipment to spot the resort''s African wildlife — zebras, giraffes, wildebeest, and more. A dramatically different experience from the daytime savanna views. No park admission required. Note: Evening departures — reservations required.', '$89–$99 + tax (varies by date)', 94.0, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-disney-private-vip-tours', 'Disney Private VIP Tours', 'All parks', 'experience', 'A fully private guided park experience led by an official Disney VIP Tour Guide. Includes expedited attraction entry, personalized itinerary planning, inter-park transportation, and exclusive accommodations throughout. Park admission required separately. Price is per group, per hour — most economical when split among the maximum 10 guests. The most seamless way to experience multiple parks in a single day. Note: Book at least 60 days in advance — call (407) 560-4033. Discount: AP discounts may apply.', '$425–$900+/hour (min. 7 hrs; up to 10 guests)', 662.5, null, ARRAY['Year-Round','Unique Tours','Per Group','Per Hour']::text[]),
  ('ex-disneys-keys-to-the-kingdom-tour', 'Disney''s Keys to the Kingdom Tour', 'MK', 'experience', 'A 5-hour walking tour of Magic Kingdom that goes where regular guests cannot — including a guided visit to the famous underground utilidor tunnel system that runs beneath the entire park. Learn the stories behind park design, Imagineering principles, and behind-the-scenes operations. One of Disney''s most popular and long-running guided tour experiences. Requires park admission. Note: Select days — minimum age 16; verify schedule at disneyworld.com.', '$169–$189 + tax (varies by date)', 179.0, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-backstage-magic-tour', 'Backstage Magic Tour', 'All parks', 'experience', 'A 7-hour guided tour covering backstage areas of Magic Kingdom (including the utilidors), EPCOT, and Hollywood Studios, with a catered lunch. The broadest backstage tour Disney offers — a full day for guests who want a comprehensive behind-the-scenes experience. Requires park admission. Departs from EPCOT. Note: Select days — verify schedule at disneyworld.com; minimum age 18.', '~$275 + tax/person', 275.0, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-disneys-family-magic-tour', 'Disney''s Family Magic Tour', 'MK', 'experience', 'A 2-hour interactive scavenger hunt-style guided tour of Magic Kingdom designed for families with young children, ending with a special character meet-and-greet. One of Disney''s most affordable guided tour options. Requires park admission. Note: Select mornings — verify schedule at disneyworld.com.', '~$39 + tax/person', 39.0, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-wilderness-back-trail-adventure', 'Wilderness Back Trail Adventure', 'FW', 'experience', 'A 2-hour guided Segway X2 adventure through the nature trails and wooded paths of Disney''s Fort Wilderness Resort. Guests learn to ride the Segway during a brief orientation before exploring the scenic grounds. No park admission required — accessible directly at the resort. Note: Select departures — minimum age 16; minimum weight 100 lbs.', '$90–$99 + tax (varies by date)', 94.5, null, ARRAY['Year-Round','Unique Tours']::text[]),
  ('ex-fishing-excursions', 'Fishing Excursions', 'All parks', 'experience', 'Guided catch-and-release bass fishing outings on the lakes and waterways throughout Walt Disney World Resort. Experienced guides take small groups out in bass boats with all gear provided. Multiple launch locations including Fort Wilderness, Grand Floridian, Wilderness Lodge, Contemporary, and Old Key West. A surprisingly accessible activity for non-fishers — guides handle all the technical aspects. Note: Reservations required — call to book; various lakes throughout property.', 'Prices vary — call (407) 939-7529', null, null, ARRAY['Year-Round','Unique Tours','No Park Admission Required']::text[]),
  ('ex-bibbidi-bobbidi-boutique', 'Bibbidi Bobbidi Boutique', 'MK', 'experience', 'A fairy godmother-in-training transforms young guests (ages 3–12) into the Disney royalty of their choice at the boutique inside Cinderella Castle. Packages range from hair and accessories (Courtyard, starting $59.99) through full gown, accessories, and makeup (Castle, starting $189.99). Character-themed knight packages also available. One of the most requested Magic Kingdom experiences for families with young children. Also available at Disney Springs — no park admission required there. Requires park admission for the Magic Kingdom location. Note: Available daily — book at 60-day window; sells out fast.', '$59.99–$229.99 + tax (ages 3–12)', 144.99, null, ARRAY['Year-Round','Make Believe & More']::text[]),
  ('ex-capture-your-moment-magic-kingdom', 'Capture Your Moment – Magic Kingdom', 'MK', 'experience', 'A private 20-minute photo session with a Disney PhotoPass photographer at select picturesque locations in Magic Kingdom — Main Street U.S.A., Fantasyland, or Liberty Square. Includes all digital photos with downloads and standard retouching. Ideal for commemorating a first visit, milestone birthday, engagement, or anniversary. Requires park admission. Note: Reservations required — book via disneyworld.com.', 'Starting from $99', 99.0, null, ARRAY['Year-Round','Special Occasions']::text[]),
  ('ex-capture-your-moment-epcot', 'Capture Your Moment – EPCOT', 'EPCOT', 'experience', 'A private 20-minute photo session with a Disney PhotoPass photographer at a select World Showcase location in EPCOT. Lovely backdrops including the Italy pavilion, Japan, or the American Adventure. All digital downloads and retouching included. Requires park admission. Note: Reservations required — book via disneyworld.com.', 'Starting from $99', 99.0, null, ARRAY['Year-Round','Special Occasions']::text[]),
  ('ex-capture-your-moment-hollywood-studios', 'Capture Your Moment – Hollywood Studios', 'HS', 'experience', 'A private 20-minute PhotoPass photo session at a select Hollywood Studios location — Toy Story Land and Galaxy''s Edge (Millennium Falcon) are among the available settings. All digital downloads included. Requires park admission. Note: Reservations required — book via disneyworld.com.', 'Starting from $99', 99.0, null, ARRAY['Year-Round','Special Occasions']::text[]),
  ('ex-capture-your-moment-animal-kingdom', 'Capture Your Moment – Animal Kingdom', 'AK', 'experience', 'A private 20-minute photo session with a Disney PhotoPass photographer at Animal Kingdom, with the Tree of Life as the signature backdrop option. All digital downloads and retouching included. Requires park admission. Note: Reservations required — book via disneyworld.com.', 'Starting from $99', 99.0, null, ARRAY['Year-Round','Special Occasions']::text[]),
  ('ex-signature-portrait-sessions-resorts', 'Signature Portrait Sessions – Resorts', 'All parks', 'experience', 'A private 40-minute portrait session with a Disney PhotoPass photographer at select Disney Resort hotels. Longer and more refined than the Capture Your Moment park sessions — all digital downloads and retouching included. No park admission required, making this accessible to any resort guest. Ideal for formal family portraits, milestone anniversaries, or engagement photos. Note: Reservations required — select resort locations.', '$399', 399.0, null, ARRAY['Year-Round','Special Occasions','No Park Admission Required']::text[]),
  ('ex-cake-ordering', 'Cake Ordering', 'All parks', 'experience', 'Custom celebration cakes available for pickup or delivery to select Disney resort hotel rooms or restaurants. Options range from a standard Mickey celebration cake to elaborate themed creations. A practical way to add a personalized sweet moment to any birthday, anniversary, or milestone celebration during a Disney trip. Note: Order at least 48 hours in advance via Disney Dining.', 'Starting from $39', 39.0, null, ARRAY['Year-Round','Special Occasions','No Park Admission Required']::text[]),
  ('ex-in-room-floral-and-gifts', 'In-Room Floral & Gifts', 'All parks', 'experience', 'Customized gift baskets, balloon bouquets, floral arrangements, and themed merchandise sets delivered directly to Disney resort hotel rooms. A popular option for surprise celebrations — birthday packages, honeymoon arrangements, and anniversary setups are among the most requested. Order at least 24–48 hours in advance. Note: Order in advance via Disney Floral & Gifts.', 'Prices vary', null, null, ARRAY['Year-Round','Special Occasions','No Park Admission Required']::text[]),
  ('ex-amorettes-patisserie-cake-decorating-experience', 'Amorette''s Patisserie Cake Decorating Experience', 'DS', 'experience', 'A hands-on cake decorating class at Amorette''s Patisserie where a skilled pastry artist guides guests through decorating their own Mickey-shaped dome cake. One reservation accommodates up to two guests — a fun option for couples or parent-and-child pairs. Take the finished cake home at the end. No park admission required. Note: Reservations required — book via disneyworld.com.', 'Starting from $199 (up to 2 guests per reservation)', 199.0, null, ARRAY['Year-Round','Special Occasions','No Park Admission Required']::text[]),
  ('ex-disneys-hoop-dee-doo-musical-revue', 'Disney''s Hoop-Dee-Doo Musical Revue', 'FW', 'experience', 'Walt Disney World''s longest-running dinner show — an all-you-care-to-enjoy Western BBQ feast (fried chicken, smoked ribs, corn, beans, strawberry shortcake) accompanied by a live country-comedy stage revue. Non-alcoholic beverages included; beer, wine, and sangria available. Two dining plan TS credits. Among the most beloved resort experiences — reserve at the 60-day window. No park admission required. Note: 3 shows nightly: 5:15 PM, 7:30 PM, 9:30 PM — book at 60-day window.', '$75–$85/adult, $47/child (3–9) + tax', 80.0, null, ARRAY['Year-Round','Adventures in Dining']::text[]),
  ('ex-spirit-of-aloha-dinner-show', 'Spirit of Aloha Dinner Show', 'POLY', 'experience', 'A Polynesian luau dinner show on the shores of the Seven Seas Lagoon at the Polynesian Resort. Polynesian song and dance, fire knife performance, and an all-you-care-to-enjoy dinner of tropical dishes with specialty cocktails. A timeless resort tradition with particularly beautiful waterfront views. No park admission required. Note: Shows at 5:15 PM and 8:00 PM — reservations required.', '~$79–$119/adult (varies by seating category) + tax', 99.0, null, ARRAY['Year-Round','Adventures in Dining']::text[]),
  ('ex-the-garden-view-lounge-tea-experience', 'The Garden View Lounge – Tea Experience', 'GF', 'experience', 'A traditional British afternoon tea inside the elegantly appointed Garden View Lounge at Disney''s Grand Floridian Resort. Finger sandwiches, freshly baked scones with clotted cream and jam, and a rotating selection of pastries — all paired with premium loose-leaf teas. A refined, unhurried experience with lovely garden courtyard views. No park admission required. Note: Reservations required — book via Disney Dining at 60-day window.', 'Starting from $79/adult, $49/child + tax & gratuity', 64.0, null, ARRAY['Year-Round','Adventures in Dining','No Park Admission Required']::text[]),
  ('ex-sangria-university', 'Sangria University', 'CSR', 'experience', 'A guided sangria exploration class at Coronado Springs Resort where a host walks guests through the history, regional varieties, and flavor profiles of sangria before guiding them through making their own custom batch. Light accompaniments included. A fun, social activity well-suited for couples or adult groups. No park admission required. Note: Reservations required — book via Disney Dining.', 'Starting from $59/person', 59.0, null, ARRAY['Year-Round','Adventures in Dining','No Park Admission Required']::text[]),
  ('ex-la-cava-experience', 'La Cava Experience', 'EPCOT', 'experience', 'A guided tasting hosted by a certified Tequila Ambassador inside La Cava del Tequila in the Mexico pavilion. Guests are walked through the history, production methods, and flavor spectrum of tequila, sampling multiple expressions alongside traditional accompaniments. One of EPCOT''s most immersive beverage experiences for adults. Requires EPCOT park admission. Note: Reservations required — small group; book via Disney Dining.', 'Starting from $180/person', 180.0, null, ARRAY['Year-Round','Adventures in Dining']::text[]),
  ('ex-learn-how-to-taste-wine-with-master-sommelier-george-miliotes', 'Learn How to Taste Wine with Master Sommelier George Miliotes', 'DS', 'experience', 'An intimate wine education experience hosted by George Miliotes — one of only 279 Master Sommeliers worldwide and owner of Wine Bar George at Disney Springs. Sessions cover tasting technique, grape varietals, wine regions, and food pairing, with guided sampling throughout. A genuinely rare opportunity to learn from a true industry expert in a Disney setting. No park admission required. Note: Select dates — book via Wine Bar George; limited availability.', 'Prices vary — check disneyworld.com', null, null, ARRAY['Year-Round','Adventures in Dining','No Park Admission Required']::text[]),
  ('ex-epcot-international-food-and-wine-festival-concert-series-dining-package', 'EPCOT International Food & Wine Festival Concert Series Dining Package', 'EPCOT', 'experience', 'A dining package at select EPCOT restaurants that includes a meal and guaranteed reserved seating for that evening''s Eat to the Beat Concert during the Food & Wine Festival. Acts rotate nightly across the festival''s run — past performers include Hanson, Boyz II Men, and similar pop acts. Requires park admission. Note: Available on Eat to the Beat concert nights — book at 60-day window.', 'Prices vary by restaurant', null, '{"festival":"Food & Wine","start":"08-27","end":"11-21","ticket_required":false}'::jsonb, ARRAY['Season','Adventures in Dining']::text[]),
  ('ex-epcot-festival-of-the-arts-disney-on-broadway-dining-package', 'EPCOT Festival of the Arts Disney on Broadway Dining Package', 'EPCOT', 'experience', 'A dining package at select EPCOT restaurants that includes a meal and guaranteed seating for a Disney on Broadway Concert Series performance during the Festival of the Arts. Broadway performers from current and past Disney productions take the America Gardens stage. One of the more special entertainment experiences EPCOT offers. Requires park admission. Note: Available on concert nights — book at 60-day window.', 'Prices vary by restaurant', null, '{"festival":"Festival of the Arts","start":"01-16","end":"02-23","ticket_required":false}'::jsonb, ARRAY['Season','Adventures in Dining']::text[]),
  ('ex-epcot-flower-and-garden-garden-rocks-dining-package', 'EPCOT Flower & Garden Garden Rocks Dining Package', 'EPCOT', 'experience', 'A dining package at select EPCOT restaurants that bundles a meal with guaranteed reserved seating for a Garden Rocks Concert during the Flower & Garden Festival. Acts lean toward nostalgic pop and rock. Requires park admission. Note: Available on Garden Rocks concert nights — book at 60-day window.', 'Prices vary by restaurant', null, '{"festival":"Flower & Garden","start":"03-04","end":"06-01","ticket_required":false}'::jsonb, ARRAY['Season','Adventures in Dining']::text[]),
  ('ex-epcot-candlelight-processional-dining-package', 'EPCOT Candlelight Processional Dining Package', 'EPCOT', 'experience', 'Guaranteed reserved seating for the Candlelight Processional — a celebrity narrator tells the Nativity story alongside a live orchestra and mass choir — bundled with a meal at a select EPCOT restaurant. Without a dining package, standby lines can be 1–3 hours. Participating restaurants include Biergarten, Coral Reef, Garden Grill, Le Cellier, and others. Requires park admission. Note: Daily during Festival of the Holidays — celebrity narrators announced closer to season.', 'Varies by restaurant ($55–$110/adult)', 82.5, '{"festival":"Festival of the Holidays","start":"11-27","end":"12-30","ticket_required":false}'::jsonb, ARRAY['Season','Adventures in Dining']::text[]),
  ('ex-magic-kingdom-fireworks-dessert-party-pre-party-tomorrowland-terrace', 'Magic Kingdom Fireworks Dessert Party – Pre-Party (Tomorrowland Terrace)', 'MK', 'experience', 'An all-you-care-to-enjoy dessert buffet at Tomorrowland Terrace before the Happily Ever After fireworks, followed by reserved viewing from the terrace during the show. The buffet features themed desserts, chocolate fondue, fresh fruit, and non-alcoholic beverages. Doors open approximately 30 minutes before the show. One of the best ways to guarantee a prime fireworks seat. Requires park admission. Note: Reservations required — book via Disney Dining at 60-day window.', '$99–$109/adult, $59/child (3–9) + tax', 104.0, null, ARRAY['Year-Round','Spectacular Sweet Spots']::text[]),
  ('ex-magic-kingdom-fireworks-dessert-party-post-party-tomorrowland-terrace', 'Magic Kingdom Fireworks Dessert Party – Post-Party (Tomorrowland Terrace)', 'MK', 'experience', 'Reserved Tomorrowland Terrace viewing during the Happily Ever After fireworks, followed by the dessert buffet after the show concludes. An alternative for guests who''d rather watch first and eat after. Same dessert spread as the pre-party version — a sweet cap to a full park day. Requires park admission. Note: Reservations required — book via Disney Dining at 60-day window.', '$99–$109/adult, $59/child (3–9) + tax', 104.0, null, ARRAY['Year-Round','Spectacular Sweet Spots']::text[]),
  ('ex-magic-kingdom-fireworks-dessert-party-seats-and-sweets-tomorrowland-terrace', 'Magic Kingdom Fireworks Dessert Party – Seats & Sweets (Tomorrowland Terrace)', 'MK', 'experience', 'The premium tier of the Tomorrowland Terrace fireworks experience — reserved outdoor table seating during the dessert buffet and fireworks simultaneously. Guests eat and watch at the same time from dedicated tables on the terrace. The most immersive and comfortable of the three MK dessert party configurations. Requires park admission. Note: Reservations required — book via Disney Dining at 60-day window.', '$124–$134/adult, $74/child (3–9) + tax', 129.0, null, ARRAY['Year-Round','Spectacular Sweet Spots']::text[]),
  ('ex-disneys-not-so-spooky-spectacular-dessert-party-tomorrowland-terrace', 'Disney''s Not-So-Spooky Spectacular Dessert Party – Tomorrowland Terrace', 'MK', 'experience', 'A Halloween-themed dessert party at Tomorrowland Terrace with reserved fireworks viewing on MNSSHP party nights. Themed treats and a dedicated seating area for Disney''s Not-So-Spooky Spectacular. Requires both a party ticket and a dessert party booking — a premium upgrade for party guests who want guaranteed views. Note: MNSSHP ticket required; separate dessert party reservation also required.', 'Starting from $124 + tax', 124.0, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Select Nights','Spectacular Sweet Spots']::text[]),
  ('ex-disneys-not-so-spooky-spectacular-dessert-party-plaza-garden', 'Disney''s Not-So-Spooky Spectacular Dessert Party – Plaza Garden', 'MK', 'experience', 'A more affordable MNSSHP dessert party option with reserved outdoor standing viewing at Plaza Garden. Same themed dessert concept at a lower price point with a different viewing angle for the Not-So-Spooky Spectacular fireworks. Note: MNSSHP ticket required; separate dessert party reservation also required.', 'Starting from $99 + tax', 99.0, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Select Nights','Spectacular Sweet Spots']::text[]),
  ('ex-minnies-wonderful-christmastime-fireworks-dessert-party', 'Minnie''s Wonderful Christmastime Fireworks Dessert Party', 'MK', 'experience', 'A festive dessert party with reserved viewing for Minnie''s Wonderful Christmastime Fireworks, available exclusively on MVMCP party nights. Holiday-themed treats and a dedicated viewing area at Tomorrowland Terrace. Requires both a party ticket and dessert party reservation. Note: MVMCP ticket required; separate dessert party reservation also required.', '~$99–$124 + tax', 111.5, '{"festival":"MVMCP","start":"11-08","end":"12-22","ticket_required":true}'::jsonb, ARRAY['Select Nights','Spectacular Sweet Spots']::text[]),
  ('ex-epcot-luminous-fireworks-dining-package-rose-and-crown', 'EPCOT Luminous Fireworks Dining Package – Rose & Crown', 'EPCOT', 'experience', 'Prix-fixe dining at Rose & Crown in the UK pavilion — appetizer, entrée, dessert, and unlimited select beverages — followed by guaranteed reserved patio seating overlooking World Showcase Lagoon for Luminous: The Symphony of Us. One of EPCOT''s most sought fireworks dining reservations. Requires park admission. Note: Reservations required — book via Disney Dining at 60-day window.', 'Starting from $92/adult (prix-fixe; varies)', 92.0, null, ARRAY['Year-Round','Spectacular Sweet Spots']::text[]),
  ('ex-epcot-luminous-fireworks-dining-package-spice-road-table', 'EPCOT Luminous Fireworks Dining Package – Spice Road Table', 'EPCOT', 'experience', 'Mediterranean small plates dining at Spice Road Table in the Morocco pavilion with a covered outdoor reserved area for Luminous: The Symphony of Us. A moderately priced alternative to the Rose & Crown package with a different lagoon perspective. Requires park admission. Note: Reservations required — book via Disney Dining.', 'Starting from $81/adult (prix-fixe; varies)', 81.0, null, ARRAY['Year-Round','Spectacular Sweet Spots']::text[]),
  ('ex-geo-82-fireworks-experience', 'GEO-82 Fireworks Experience', 'EPCOT', 'experience', 'An exclusive adults-only (21+) fireworks lounge experience at GEO-82 with artisan light bites, sparkling beverages, and Luminous fireworks views from a dedicated adults-only rooftop space. The most premium EPCOT fireworks package — not the closest vantage point but the most intimate atmosphere. Requires park admission. Note: Reservations required — adults only (21+).', '$179/person + tax & gratuity', 179.0, null, ARRAY['Year-Round','Spectacular Sweet Spots','Adults Only (21+)']::text[]),
  ('ex-celebration-at-the-top-sip-savor-sparkle', 'Celebration at the Top – Sip, Savor, Sparkle', 'CR', 'experience', 'A rooftop fireworks experience atop Disney''s Contemporary Resort with curated hors d''oeuvres, themed mini desserts, and specialty beverages served while watching the Magic Kingdom Happily Ever After fireworks from an elevated outdoor terrace. One of the most dramatic fireworks vantage points at Walt Disney World. No park admission required. Note: Reservations required — adults recommended; book via Disney Dining.', 'Starting from $169/person', 169.0, null, ARRAY['Year-Round','Spectacular Sweet Spots','No Park Admission Required']::text[]),
  ('ex-magic-kingdom-epcot-fireworks-cruise', 'Magic Kingdom / EPCOT Fireworks Cruise', 'All parks', 'experience', 'A private pontoon boat charter for watching Magic Kingdom or EPCOT fireworks from the water — Seven Seas Lagoon or World Showcase Lagoon respectively. Up to 10 guests per boat; specialty food and beverages available to pre-order. Price is per boat — excellent value when divided among a larger group. No park admission required. Note: Reservations required — priced per boat, not per person.', 'Starting from $499/boat (up to 10 guests)', 499.0, null, ARRAY['Year-Round','Spectacular Sweet Spots','No Park Admission Required','Per Group']::text[]),
  ('ex-jazzy-holidays-at-the-hollywood-brown-derby', 'Jazzy Holidays at the Hollywood Brown Derby', 'HS', 'experience', 'A live jazz performance inside the Hollywood Brown Derby during Disney Jollywood Nights, featuring holiday standards and Disney favorites performed by a sophisticated ensemble. An event-exclusive menu of craft cocktails and small plates is available. A quieter, more adult-oriented corner of the Jollywood Nights experience. Requires a Jollywood Nights ticket. Note: Jollywood Nights ticket required — walk-up or reservation.', 'Prices vary (cocktails and bites à la carte)', null, '{"festival":"Jollywood Nights","start":"11-07","end":"01-05","ticket_required":true}'::jsonb, ARRAY['Select Nights','Spectacular Sweet Spots']::text[]),
  ('ex-typhoon-lagoon-surfing-programs', 'Typhoon Lagoon Surfing Programs', 'TL', 'experience', 'Surfing lessons in the massive wave pool at Disney''s Typhoon Lagoon, held before the park opens to the general public. Open sessions are group classes (multiple participants); private sessions are for individuals or small groups with exclusive pool access. Surfboards, rash guards, and instruction provided. A genuinely thrilling experience — the wave pool generates consistent 6-foot-plus waves. Note: Open and private surf sessions available — book in advance.', 'Starting from $325 (group); private sessions available', 325.0, null, ARRAY['Year-Round','Rest & Recreation']::text[]),
  ('ex-beachcomber-shacks-typhoon-lagoon-standard', 'Beachcomber Shacks – Typhoon Lagoon Standard', 'TL', 'experience', 'A reserved private shaded area at Typhoon Lagoon with cushioned lounge chairs, a complimentary dry storage locker, and priority access to the reserved zone. Includes a cooler with water and a towel service credit. Capacity varies by shack — accommodates up to 6 guests. Requires water park admission. Note: Reservations recommended — limited availability.', 'Starting from $225/day', 225.0, null, ARRAY['Year-Round','Rest & Recreation']::text[]),
  ('ex-beachcomber-shacks-typhoon-lagoon-deluxe', 'Beachcomber Shacks – Typhoon Lagoon Deluxe', 'TL', 'experience', 'An upgraded private shaded area at Typhoon Lagoon with the same cushioned seating and cooler as the Standard plus additional premium amenities. A larger footprint and closer proximity to key slides. Accommodates up to 8 guests. Requires water park admission. Note: Reservations recommended — limited availability.', 'Starting from $300/day', 300.0, null, ARRAY['Year-Round','Rest & Recreation']::text[]),
  ('ex-beachcomber-shacks-typhoon-lagoon-premium-plus', 'Beachcomber Shacks – Typhoon Lagoon Premium Plus', 'TL', 'experience', 'Typhoon Lagoon''s most premium reserved area, featuring cushioned seating, a mini fridge, a flat-screen TV, and a dedicated server for food and beverage orders. The most resort-like experience available at a Disney water park. Requires water park admission. Note: Reservations recommended — limited availability.', 'Starting from $375/day', 375.0, null, ARRAY['Year-Round','Rest & Recreation']::text[]),
  ('ex-polar-patios-blizzard-beach-standard', 'Polar Patios – Blizzard Beach Standard', 'BB', 'experience', 'A reserved private shaded deck at Blizzard Beach alongside Cross Country Creek with lounge seating, a complimentary cooler, and towel service. Accommodates up to 10 guests. A significant quality-of-life upgrade for a full day at the water park. Requires water park admission. Note: Reservations recommended — limited availability.', 'Starting from $225/day', 225.0, null, ARRAY['Year-Round','Rest & Recreation']::text[]),
  ('ex-polar-patios-blizzard-beach-premium-plus', 'Polar Patios – Blizzard Beach Premium Plus', 'BB', 'experience', 'Blizzard Beach''s top-tier reserved deck with upgraded seating, additional shade coverage, and premium amenities. The most comfortable way to spend a full day at the water park. Accommodates up to 10 guests. Requires water park admission. Note: Reservations recommended — limited availability.', 'Starting from $375/day', 375.0, null, ARRAY['Year-Round','Rest & Recreation']::text[]),
  ('ex-lodge-umbrellas-blizzard-beach', 'Lodge Umbrellas – Blizzard Beach', 'BB', 'experience', 'Reserved umbrella and lounge chair sets at Blizzard Beach for guests who want shade without the full cabana commitment. Includes two loungers and an umbrella along the beach area. First-come, first-served at the rental desk. Requires water park admission. Note: Available day-of at the park — no advance reservation.', '$49–$109 (varies by date)', 79.0, null, ARRAY['Year-Round','Rest & Recreation']::text[]),
  ('ex-typhoon-lagoon-umbrellas', 'Typhoon Lagoon Umbrellas', 'TL', 'experience', 'Reserved umbrella and lounge chair sets along the beach at Typhoon Lagoon. A budget-friendly alternative to the Beachcomber Shacks for guests who primarily want shade and a home base without the full private area. Requires water park admission. Note: Available day-of at the park.', '$49–$109 (varies by date)', 79.0, null, ARRAY['Year-Round','Rest & Recreation']::text[]),
  ('ex-fantasia-gardens-miniature-golf', 'Fantasia Gardens Miniature Golf', 'All parks', 'experience', 'Two 18-hole miniature golf courses near the Swan & Dolphin and EPCOT resort area — Fantasia Gardens (skill-based with Fantasia theming) and Fantasia Fairways (a traditional golf-style layout). A great off-park activity for families looking for a lower-cost, lower-intensity Disney day. No park admission required. Note: Walk-up or call (407) 939-7529 to book.', 'Starting from $19 + tax', 19.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-winter-summerland-miniature-golf', 'Winter Summerland Miniature Golf', 'AKL', 'experience', 'Two 18-hole Santa-themed miniature golf courses near Blizzard Beach — a summer-themed Sandcastle course and a winter-themed Snow course. A fun family activity that plays up the Florida-meets-winter theme with clever holes and Disney Easter eggs. No park admission required. Note: Walk-up or call (407) 939-7529 to book.', 'Starting from $19 + tax', 19.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-disneys-magnolia-golf-course', 'Disney''s Magnolia Golf Course', 'FW', 'experience', 'A championship 18-hole Tour-style course — one of Disney''s most prestigious golf offerings, known for the Mickey-shaped sand trap on the 6th hole. Designed to challenge serious golfers with strategic water hazards and elevated greens. Full pro shop, club rentals, and golf cart included. No park admission required. Note: Advance tee times strongly recommended.', 'Prices vary — call (407) 939-4653', null, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-disneys-palm-golf-course', 'Disney''s Palm Golf Course', 'FW', 'experience', 'An 18-hole championship course through Florida woodlands with natural beauty and strategic challenges. One of the PGA Tour''s former Florida swing venues. Full amenities including pro shop, club rentals, and cart. No park admission required. Note: Advance tee times strongly recommended.', 'Prices vary — call (407) 939-4653', null, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-disneys-oak-trail-golf-course', 'Disney''s Oak Trail Golf Course', 'FW', 'experience', 'A walking 9-hole, par-36 course designed for families and casual golfers — no carts, intentionally relaxed pace. Disney''s most approachable golf experience. A great introduction to golf for younger guests or non-serious players. Club rentals available. No park admission required. Note: Walk-ins often available; tee times recommended.', 'Prices vary — call (407) 939-4653', null, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-disneys-lake-buena-vista-golf-course', 'Disney''s Lake Buena Vista Golf Course', 'DS', 'experience', 'A classic country club-style 18-hole course winding through pastel villas, palm trees, and sparkling lakes near Disney Springs. More residential in character than the Magnolia and Palm courses — a pleasant, well-maintained round without the premium price. No park admission required. Note: Advance tee times recommended.', 'Prices vary — call (407) 939-4653', null, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-footgolf-at-disneys-oak-trail', 'FootGolf at Disney''s Oak Trail', 'FW', 'experience', 'A hybrid sport combining soccer and golf on the Oak Trail course — players kick a soccer ball into oversized holes using golf rules and scoring. A fun, accessible activity for mixed-age groups and families with athletic teens. No experience or equipment beyond athletic shoes required. No park admission required. Note: Walk-ins welcome — call (407) 939-4653 for details.', 'Starting from $25', 25.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-horseback-riding-at-fort-wilderness', 'Horseback Riding at Fort Wilderness', 'FW', 'experience', 'Guided trail rides through the wooded nature paths of Fort Wilderness Resort aboard well-mannered horses. 45-minute guided group rides through scenic Florida wilderness. A peaceful, unexpected way to experience Walt Disney World away from the parks. No park admission required. Note: Reservations required — call (407) 939-7529; minimum age 9; max. weight 250 lbs.', 'Starting from $65', 65.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-horse-drawn-carriage-rides-fort-wilderness', 'Horse-Drawn Carriage Rides – Fort Wilderness', 'FW', 'experience', 'An evening horse-drawn carriage ride along the scenic wooded trails around Fort Wilderness Resort — a slower, more romantic alternative to the guided trail rides. A lovely option for couples or families looking for a quiet end-of-day activity. No park admission required. Note: Reservations required — call (407) 939-7529; evening departures only.', 'Starting from $65', 65.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-horse-drawn-carriage-rides-port-orleans-riverside', 'Horse-Drawn Carriage Rides – Port Orleans Riverside', 'PORS', 'experience', 'Evening horse-drawn carriage rides along the banks of the Sassagoula River at Port Orleans Riverside. A romantic, unhurried experience particularly popular with couples and guests celebrating special occasions. No park admission required. Note: Reservations required — call (407) 939-7529.', 'Starting from $65', 65.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-pony-rides-at-fort-wilderness', 'Pony Rides at Fort Wilderness', 'FW', 'experience', 'Short, guided pony rides at the Tri-Circle D Ranch stables at Fort Wilderness — a simple, joyful introduction to horses for the youngest Disney guests. Walk-in only; one of the few Enchanting Extras that doesn''t require advance reservations. No park admission required. Note: Walk-in only — no reservations.', 'Starting from $10 + tax', 10.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-fort-wilderness-archery-experience', 'Fort Wilderness Archery Experience', 'FW', 'experience', 'A 75-minute guided archery session at Fort Wilderness for guests ages 7 and up. An experienced instructor walks participants through proper form, technique, and safety before they try their hand at target shooting. No experience necessary — suitable for complete beginners. No park admission required. Note: Reservations required; minimum age 7.', 'Starting from $49 + tax', 49.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-wilderness-back-trail-adventure-segway', 'Wilderness Back Trail Adventure – Segway', 'FW', 'experience', 'A 2-hour guided Segway X2 adventure through the nature trails and scenic areas of Fort Wilderness Resort. Includes a brief orientation and safety lesson before setting off through wooded paths, past the resort''s lakes, and through natural Florida landscape. No park admission required. Note: Reservations required; minimum age 16; minimum weight 100 lbs.', '$90–$99 + tax (varies by date)', 94.5, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-arts-and-crafts-mosaics', 'Arts & Crafts: Mosaics', 'All parks', 'experience', 'A guided hands-on mosaic art class where guests learn the fundamentals of mosaic design and create their own take-home piece — typically a Mickey or Minnie-shaped artwork. Suitable for adults and older children. A relaxing creative activity between park days. No park admission required. Note: Reservations required — check availability at select resort locations.', 'Starting from $30', 30.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-colors-of-coronado-painting-experience', 'Colors of Coronado Painting Experience', 'CSR', 'experience', 'A guided painting class at Coronado Springs Resort where a local artist leads participants through painting a Disney-themed canvas to take home. Past subjects have included Cinderella Castle with fireworks and various Disney park scenes. A relaxing creative activity well-suited for guests taking a day off from the parks. No park admission required. Note: Reservations required — check availability at Coronado Springs.', 'Starting from $45', 45.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-aerophile-tethered-balloon-flight', 'Aerophile Tethered Balloon Flight', 'DS', 'experience', 'A ride aboard the world''s largest tethered helium balloon at Disney Springs, rising approximately 400 feet above the ground for panoramic views of the Walt Disney World resort area. The flight lasts about 8–10 minutes and accommodates up to 30 guests per ascent. Walk-up only — no advance reservations. Subject to weather cancellations. Note: Walk-up tickets purchased in person only at the balloon.', 'Starting from $24.99/person', 24.99, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-the-grand-floridian-spa', 'The Grand Floridian Spa', 'GF', 'experience', 'A full-service spa and salon inside Disney''s Grand Floridian Resort offering massages, body wraps, facials, manicures, pedicures, and hair styling. A luxurious retreat from the parks — popular for birthday pampering, honeymoon add-ons, and mid-trip recovery days. No park admission required. Note: Reservations recommended — call (407) 824-3000.', 'Prices vary by treatment', null, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-mandara-spa-at-swan-and-dolphin', 'Mandara Spa at Swan & Dolphin', 'SWD', 'experience', 'A full-service luxury spa at the Walt Disney World Swan & Dolphin Resort with a comprehensive menu of massages, body treatments, facials, manicures, and pedicures. Slightly more affordable than the Grand Floridian Spa with equivalent service quality. No park admission required. Note: Reservations recommended — call the spa directly.', 'Prices vary by treatment', null, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-poolside-patios-deluxe-resort-pools', 'Poolside Patios – Deluxe Resort Pools', 'All parks', 'experience', 'Reserved private poolside patio areas with lounge chairs, towels, and shade at select Disney deluxe resort hotels. A comfortable upgrade for resort guests spending the day at the pool rather than in the parks. No park admission required — guests staying at the applicable resort receive priority. Note: Call to book — available at select deluxe resort pools.', '$109–$119 + tax (varies by date and location)', 114.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-resort-cabanas', 'Resort Cabanas', 'All parks', 'experience', 'Private poolside cabanas at select Disney resort hotels with premium amenities including shaded seating, dedicated attendant service, and in-cabana food and beverage ordering. Available at select deluxe and moderate resort properties. No park admission required. Note: Call to book — available at select resort pools.', 'Prices vary — call (407) 939-7529', null, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-vintage-amphicar-tours', 'Vintage Amphicar Tours', 'DS', 'experience', 'A 20-minute captain-guided tour of Lake Buena Vista aboard a fully restored vintage Amphicar — a rare 1960s vehicle that drives on land and floats on water. The Amphicar drives into the lake directly from the dock at The BOATHOUSE at Disney Springs. One of the most unique and photo-worthy experiences at Walt Disney World. In-person reservations only at the dock. No park admission required. Note: Walk-up reservations at The BOATHOUSE dock; subject to weather and availability.', 'Starting from $125 — in-person reservations only at The BOATHOUSE', 125.0, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-splitsville-luxury-lanes', 'Splitsville Luxury Lanes', 'DS', 'experience', 'An upscale bowling alley and restaurant at Disney Springs with 30 lanes, billiards, an extensive menu, and a full bar. Open late — a popular evening activity for groups and families. Lane reservations recommended during peak hours and weekends. No park admission required. Note: Walk-in or call for reservations — (407) 938-7467.', 'Prices vary — call for group rates', null, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-level99', 'Level99', 'DS', 'experience', 'An adult-oriented entertainment venue at Disney Springs with over 60 life-sized physical challenges and games — from balance puzzles to reaction challenges to coordination games — plus handcrafted cocktails, Detroit-style pizza, and a full restaurant. Designed for adults but older teens can participate. No park admission required. Note: Walk-in or advance booking available — level99.com.', 'Prices vary by time and day', null, null, ARRAY['Year-Round','Rest & Recreation','No Park Admission Required']::text[]),
  ('ex-star-wars-galaxys-edge-savis-workshop-handbuilt-lightsabers', 'Star Wars: Galaxy''s Edge Savi''s Workshop – Handbuilt Lightsabers', 'HS', 'experience', 'A 20-minute theatrical experience in Galaxy''s Edge where guests select a lightsaber theme and hand-build their own custom saber — kyber crystal, hilt, and all. The room dims, Force-themed music plays, and the completed saber illuminates for the first time in an emotional moment that guests genuinely remember. Four themes available: Peace and Justice, Power and Control, Elemental Nature, Protection and Defense. Requires park admission. Note: Reservations required — book at 60-day window; sells out quickly.', 'Starting from $274.99/lightsaber', 274.99, null, ARRAY['Year-Round','Make Believe & More']::text[]),
  ('ex-star-wars-galaxys-edge-droid-depot', 'Star Wars: Galaxy''s Edge Droid Depot', 'HS', 'experience', 'Build a custom astromech droid (R-series or BB-series) at the Droid Depot workbench in Galaxy''s Edge. Choose components from a conveyor belt, assemble the droid, and activate it. The finished droid interacts with sensors and elements throughout the land. Personality chips and additional accessories available for purchase. Requires park admission. Note: Walk-up sometimes available; reservations recommended on busy days.', 'Starting from $129.99/droid', 129.99, null, ARRAY['Year-Round','Make Believe & More']::text[]),
  ('ex-harmony-barber-shop', 'Harmony Barber Shop', 'MK', 'experience', 'A charmingly old-fashioned barbershop on Main Street U.S.A. offering haircuts for guests of all ages. The real draw for young guests: the First Haircut experience with a special certificate, Mickey ears with the child''s name, and a small bag of clipped hair to take home. Walk-ins welcome; can get busy by mid-morning. Requires park admission. Note: Walk-in or book a day ahead; opens at park open.', 'Prices vary by service', null, null, ARRAY['Year-Round','Make Believe & More']::text[]),
  ('ex-drawn-to-life-by-cirque-du-soleil', 'Drawn to Life by Cirque du Soleil', 'DS', 'experience', 'A permanent Cirque du Soleil production created exclusively for Disney Springs, blending Disney animation with the acrobatics and spectacle of Cirque du Soleil. The story follows a young girl who enters a world of animated Disney drawings brought to life. One of the most unique entertainment experiences in the Walt Disney World resort area. Runs approximately 90 minutes. No park admission required. Note: Advance reservations strongly recommended — book at cirquedusoleil.com.', 'Starting from ~$89/adult, ~$69/child', 79.0, null, ARRAY['Year-Round','Make Believe & More','No Park Admission Required']::text[])
on conflict (id) do update set name=excluded.name, park=excluded.park, category=excluded.category, description=excluded.description, price_label=excluded.price_label, price_mid=excluded.price_mid, seasonal=excluded.seasonal, tags=excluded.tags;
