-- Location Detail values for the dining catalog, from an updated version
-- of the source spreadsheet (wdw_dining_v3 (1).xlsx). Only 80 of the 225
-- restaurants have a value in the sheet -- the rest are left null rather
-- than guessed.
update catalog_items as c set location_detail = v.loc
from (values
  ('d-50-s-prime-time-caf', 'Echo Lake'),
  ('d-akershus-royal-banquet-hall', 'World Showcase'),
  ('d-beak-and-barrel', 'Adventureland'),
  ('d-biergarten-restaurant', 'World Showcase'),
  ('d-bog', 'Fantasyland'),
  ('d-brownderby', 'Hollywood Blvd'),
  ('d-chefs-de-france', 'World Showcase'),
  ('d-coral-reef-restaurant', 'World Nature'),
  ('d-crt', 'Fantasyland'),
  ('d-garden-grill', 'World Nature'),
  ('d-hollywood-and-vine', 'Hollywood Blvd'),
  ('d-la-hacienda-de-san-angel', 'World Showcase'),
  ('d-le-cellier-steakhouse', 'World Showcase'),
  ('d-le-creperie-de-paris', 'World Showcase'),
  ('d-liberty-tree-tavern', 'Liberty Square'),
  ('d-monsieur-paul', 'World Showcase'),
  ('d-nine-dragons-restaurant', 'World Showcase'),
  ('d-nomad-lounge', 'Discovery Island'),
  ('d-rainforest-cafe', 'Oasis'),
  ('d-rose-and-crown-dining-room', 'World Showcase'),
  ('d-roundup-rodeo-bbq', 'Toy Story Land'),
  ('d-san-angel-inn-restaurante', 'World Showcase'),
  ('d-scifi', 'Echo Lake'),
  ('d-shiki-sai-sushi-izakaya', 'World Showcase'),
  ('d-skipper', 'Adventureland'),
  ('d-space220', 'World Discovery'),
  ('d-spice-road-table', 'World Showcase'),
  ('d-teppan-edo', 'World Showcase'),
  ('d-the-crystal-palace', 'Main Street U.S.A.'),
  ('d-the-diamond-horseshoe', 'Frontierland'),
  ('d-the-hollywood-brown-derby', 'Hollywood Blvd'),
  ('d-the-plaza-restaurant', 'Main Street U.S.A.'),
  ('d-tiffins-restaurant', 'Discovery Island'),
  ('d-tony-s-town-square-restaurant', 'Main Street U.S.A.'),
  ('d-tusker-house-restaurant', 'Africa'),
  ('d-tutto-gusto-wine-cellar', 'World Showcase'),
  ('d-tutto-italia-ristorante', 'World Showcase'),
  ('d-via-napoli-ristorante-e', 'World Showcase'),
  ('d-yak-and-yeti-restaurant', 'Asia'),
  ('s-abc-commissary', 'Echo Lake'),
  ('s-backlot-express', 'Echo Lake'),
  ('s-casey-s-corner', 'Main Street U.S.A.'),
  ('s-catalina-eddie-s', 'Sunset Blvd'),
  ('s-columbia-harbour-house', 'Liberty Square'),
  ('s-connections-cafe-and-eatery', 'World Celebration'),
  ('s-cosmic-ray-s-starlight-cafe', 'Tomorrowland'),
  ('s-cr-pes-emporter', 'World Showcase'),
  ('s-creature-comforts', 'Discovery Island'),
  ('s-docking-bay-7-food-and-cargo', 'Galaxy''s Edge'),
  ('s-dockside-diner', 'Toy Story Land'),
  ('s-fairfax-fare', 'Sunset Blvd'),
  ('s-fife-and-drum-tavern', 'World Showcase'),
  ('s-flame-tree-barbecue', 'Discovery Island'),
  ('s-gaston-s-tavern', 'Fantasyland'),
  ('s-golden-oak-outpost', 'Frontierland'),
  ('s-harambe-market', 'Africa'),
  ('s-katsura-grill', 'World Showcase'),
  ('s-kringla-bakeri-og-kafe', 'World Showcase'),
  ('s-la-cantina-de-san-angel', 'World Showcase'),
  ('s-les-halles-boulangerie-p', 'World Showcase'),
  ('s-lotus-blossom-cafe', 'World Showcase'),
  ('s-main-street-bakery', 'Main Street U.S.A.'),
  ('s-mr-kamal-s', 'Asia'),
  ('s-pecos-bill-tall-tale-inn-and', 'Frontierland'),
  ('s-pinocchio-village-haus', 'Fantasyland'),
  ('s-pizzafari', 'Discovery Island'),
  ('s-refreshment-outpost', 'World Showcase'),
  ('s-regal-eagle-smokehouse', 'World Showcase'),
  ('s-ronto-roasters', 'Galaxy''s Edge'),
  ('s-rosie-s-all-american-cafe', 'Sunset Blvd'),
  ('s-satu-li-canteen', 'Pandora'),
  ('s-sleepy-hollow', 'Liberty Square'),
  ('s-sommerfest', 'World Showcase'),
  ('s-sunshine-seasons', 'World Nature'),
  ('s-the-lunching-pad', 'Tomorrowland'),
  ('s-tortuga-tavern', 'Adventureland'),
  ('s-trolley-car-caf', 'Hollywood Blvd'),
  ('s-woody-s-lunch-box', 'Toy Story Land'),
  ('s-yak-and-yeti-local-food-cafes', 'Asia'),
  ('s-yorkshire-county-fish-shop', 'World Showcase')
) as v(id, loc)
where c.id = v.id;
