-- Land/Area values for the ride & show catalog, from the same source
-- spreadsheet as the original import (wdw_rides_v2.xlsx), added to the
-- location_detail field already used for dining/festival booth locations.
update catalog_items as c set location_detail = v.land
from (values
  ('r-7dmt', 'Fantasyland'),
  ('r-alien-swirling-saucers', 'Toy Story Land'),
  ('r-astro-orbiter', 'Tomorrowland'),
  ('r-btmr', 'Frontierland'),
  ('r-buzz-lightyear-s-space-ranger', 'Tomorrowland'),
  ('r-dumbo-the-flying-elephant', 'Fantasyland'),
  ('r-everest', 'Asia'),
  ('r-falcon', 'Galaxy''s Edge'),
  ('r-fop', 'Pandora'),
  ('r-frozen', 'World Showcase'),
  ('r-gotg', 'World Discovery'),
  ('r-gran-fiesta-tour-starring-the', 'World Showcase'),
  ('r-haunted', 'Liberty Square'),
  ('r-it-s-a-small-world', 'Fantasyland'),
  ('r-jungle-cruise', 'Adventureland'),
  ('r-kali-river-rapids', 'Asia'),
  ('r-living-with-the-land', 'World Nature'),
  ('r-mad-tea-party', 'Fantasyland'),
  ('r-mickey-and-minnie-s-runaway', 'Hollywood Blvd'),
  ('r-mission-space', 'World Discovery'),
  ('r-na-vi-river-journey', 'Pandora'),
  ('r-peter-pan-s-flight', 'Fantasyland'),
  ('r-pirates-of-the-caribbean', 'Adventureland'),
  ('r-primeval-whirl', 'DinoLand U.S.A.'),
  ('r-prince-charming-regal', 'Fantasyland'),
  ('r-remy', 'World Showcase'),
  ('r-rock-n-roller-coaster', 'Sunset Blvd'),
  ('r-rotr', 'Galaxy''s Edge'),
  ('r-safaris', 'Africa'),
  ('r-se', 'World Celebration'),
  ('r-slinky', 'Toy Story Land'),
  ('r-smtn', 'Tomorrowland'),
  ('r-soarin-across-america', 'World Nature'),
  ('r-sorcerers-of-the-magic-kingdom', 'Various Lands'),
  ('r-star-tours-the-adventures', 'Echo Lake'),
  ('r-testtrack', 'World Discovery'),
  ('r-the-barnstormer', 'Fantasyland'),
  ('r-the-many-adventures-of-winnie', 'Fantasyland'),
  ('r-the-seas-with-nemo-and-friends', 'World Nature'),
  ('r-the-twilight-zone-tower-of', 'Sunset Blvd'),
  ('r-tiana', 'Frontierland'),
  ('r-tom-sawyer-island', 'Frontierland'),
  ('r-tomorrowland-speedway', 'Tomorrowland'),
  ('r-toy-story-mania', 'Toy Story Land'),
  ('r-tron', 'Tomorrowland'),
  ('r-under-the-sea-journey-of-the', 'Fantasyland'),
  ('r-walt-disney-world-railroad', 'Main Street U.S.A.'),
  ('r-wildlife-express-train', 'Africa'),
  ('w-beauty-and-the-beast-live-on', 'Sunset Blvd'),
  ('w-carousel-of-progress', 'Tomorrowland'),
  ('w-disney-and-pixar-short-film', 'World Celebration'),
  ('w-disney-jr-mickey-mouse', 'Animation Courtyard'),
  ('w-fantasmic', 'Sunset Blvd'),
  ('w-feathered-friends-in-flight', 'Asia'),
  ('w-festival-of-the-lion-king', 'Africa'),
  ('w-finding-nemo-the-big-blue-and', 'Discovery Island'),
  ('w-for-the-first-time-in-forever', 'Echo Lake'),
  ('w-gorilla-falls-exploration', 'Africa'),
  ('w-indiana-jones-epic-stunt', 'Echo Lake'),
  ('w-journey-into-imagination-with', 'World Celebration'),
  ('w-maharajah-jungle-trek', 'Asia'),
  ('w-mickey-s-philharmagic', 'Fantasyland'),
  ('w-monsters-inc-laugh-floor', 'Tomorrowland'),
  ('w-muppet-vision-3d', 'Grand Avenue'),
  ('w-reflections-of-china', 'World Showcase'),
  ('w-the-little-mermaid-a-musical', 'Animation Courtyard'),
  ('w-turtle-talk-with-crush', 'World Nature'),
  ('w-up-a-great-bird-adventure', 'Asia'),
  ('w-zootopia-better-zoogether', 'Discovery Island')
) as v(id, land)
where c.id = v.id;
