-- Adds 19 Events and 19 Experiences (hard-ticket parties, EPCOT festivals,
-- After Hours, runDisney weekends, included seasonal overlays, dessert
-- parties, fireworks dining packages, VIP tours, and dinner shows) as new
-- catalog_items rows. category 'event' and 'experience' already have full
-- wish-list/expense support (WL_CAT_ORDER, WL_CAT_TO_EXPENSE_CAT in
-- src/lib/wishlist.js both map to expense category 'experience') -- no
-- frontend category work was needed, just the catalog rows.
--
-- Both tabs share the id prefix convention (ev-/ex-) and the same seasonal
-- jsonb shape used by the Food & Wine and MNSSHP catalog work. Where a row
-- ties to a party/festival that already has its own catalog rows (MNSSHP,
-- MVMCP, Food & Wine, Festival of the Holidays), it reuses that exact
-- seasonal.festival string so a family's wish-listed food items and the
-- top-level event/experience pill agree.
--
-- No new schema columns: event_type (Select Nights / Year-Round / Season)
-- and one-off flags (Per Group, Per Hour, Adults Only) go in tags, matching
-- how New 2026 / Plant-based are already handled. The source spreadsheet's
-- "Select Nights Note" and "Discounts" columns don't have a dedicated
-- field, so they're folded into the description text.
--
-- Pricing: price_label keeps the source range/estimate text verbatim;
-- price_mid is the numeric midpoint (adult+child average where both are
-- given, matching the existing Hoop-Dee-Doo dining catalog row's $80 mid
-- for its $75-85 adult range). Included-with-admission events get
-- price_mid 0. Per-boat (Fireworks Cruise) and per-guide-hour (VIP Tour)
-- items keep their raw price_mid with a 'Per Group'/'Per Hour' tag flagging
-- that it isn't a per-person number.
--
-- Only 'year_round' events with a genuine ongoing/recurring window (After
-- Hours, H2O Glow) get a seasonal date range populated, since the source
-- gives concrete 2026 dates for them despite the 'Year-Round' Event Type
-- label (which just describes cadence, not whether a window exists) --
-- evergreen bookable experiences (tours, dessert parties, dinner shows)
-- have no such window and get seasonal = null.
--
-- Typhoon Lagoon (H2O Glow After Hours) had no park code in the app's
-- WL_PARK_LABEL/WL_PARK_GROUPS -- added 'TL' there in the same commit.
-- Cross-park items (runDisney weekends, Fireworks Cruise, VIP Tour,
-- Backstage Magic Tour, NYE) use the existing 'All parks' sentinel already
-- recognized by the catalog park filter.
insert into catalog_items (id, name, park, category, description, price_label, price_mid, seasonal, tags) values
  ('ev-mickeys-not-so-scary-halloween-party', 'Mickey''s Not-So-Scary Halloween Party', 'MK', 'event', 'Magic Kingdom''s premier fall special event. Guests in costume enjoy exclusive entertainment including Mickey''s Boo-To-You Parade, Hocus Pocus Villain Spelltacular stage show, Disney''s Not-So-Spooky Spectacular fireworks, exclusive character meets, trick-or-treat candy stops, and party-exclusive food and merchandise. Entry begins at 4 PM; event runs 7 PM–midnight. Ticket includes park entry — no separate day ticket needed. Note: 36 select nights — verify dates at disneyworld.com. Discount: AP/DVC save $10 (Aug 7–Oct 2 only).', '$119–$229 + tax', 174.0, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ev-mickeys-very-merry-christmas-party', 'Mickey''s Very Merry Christmas Party', 'MK', 'event', 'Magic Kingdom''s holiday after-hours party with Mickey''s Once Upon a Christmastime Parade, Minnie''s Wonderful Christmastime Fireworks, Mickey''s Most Merriest Celebration castle stage show, holiday ride overlays, complimentary cookies and hot cocoa, snow flurries on Main Street, exclusive character meets, and party-exclusive food and merchandise. Entry begins at 4 PM; event runs 7 PM–midnight. Includes park entry — no separate day ticket needed. Note: Select nights — verify dates at disneyworld.com. Discount: AP/DVC save $10 on select nights (Nov 8–20, Nov 29–Dec 3).', '$189–$229 + tax', 209.0, '{"festival":"MVMCP","start":"11-08","end":"12-22","ticket_required":true}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ev-disney-jollywood-nights', 'Disney Jollywood Nights', 'HS', 'event', 'Hollywood Studios'' holiday after-hours party with a vintage Hollywood glamour theme. Features Jingle Bell, Jingle BAM! fireworks and projections spectacular, Disney Holidays in Hollywood stage show (hosted by Kermit and Miss Piggy), Glisten! ice skating show, rare character greetings (20+), the Twilight Soirée jazz lounge, Jazzy Holidays at the Hollywood Brown Derby, exclusive food and drinks, and shorter attraction wait times. Entry begins 5:30 PM; event runs 7:30 PM–12:30 AM. Extends into January for the first time in 2026. Note: 15 select nights — verify dates at disneyworld.com. Discount: Check disneyworld.com for AP/DVC discounts.', '$TBD (est. $125–$185 + tax)', 155.0, '{"festival":"Jollywood Nights","start":"11-07","end":"01-05","ticket_required":true}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ev-disney-after-hours-magic-kingdom', 'Disney After Hours – Magic Kingdom', 'MK', 'event', 'Separately ticketed late-night event with limited capacity and dramatically reduced wait times. Includes complimentary ice cream novelties, popcorn, and select bottled beverages. Entry from 7 PM; event runs 10 PM–1 AM. Popular attractions including Seven Dwarfs Mine Train and TRON Lightcycle / Run are open with minimal waits. Strong value for guests focused on headliner rides, though prices have risen significantly in recent years. Note: Select nights weekly — verify dates at disneyworld.com. Discount: No AP or DVC discount at Magic Kingdom.', '$175–$199 + tax', 187.0, '{"festival":"After Hours – Magic Kingdom","start":"01-12","end":"07-27","ticket_required":true}'::jsonb, ARRAY['Year-Round']::text[]),
  ('ev-disney-after-hours-hollywood-studios', 'Disney After Hours – Hollywood Studios', 'HS', 'event', 'Late-night separately ticketed event at Hollywood Studios with limited capacity and short wait times. Includes complimentary ice cream novelties, popcorn, and select beverages. Entry from 7 PM; event runs 9:30 PM–12:30 AM (10 PM–1 AM on select dates). Rise of the Resistance and Tower of Terror available with low waits. AP and DVC $30 discount makes this better value than Magic Kingdom After Hours for passholders. Note: Select nights — verify dates at disneyworld.com. Discount: AP/DVC save $30.', '$155–$189 + tax', 172.0, '{"festival":"After Hours – Hollywood Studios","start":"01-14","end":"09-12","ticket_required":true}'::jsonb, ARRAY['Year-Round']::text[]),
  ('ev-disney-after-hours-epcot', 'Disney After Hours – EPCOT', 'EPCOT', 'event', 'EPCOT''s late-night limited-capacity event. Includes complimentary ice cream novelties, popcorn, and beverages. Entry from 7 PM; event runs 9:30 PM–12:30 AM. World Showcase pavilion snack locations remain open for purchase. Guardians of the Galaxy: Cosmic Rewind available with short waits. AP and DVC $30 discount available. Note: Select nights — verify dates at disneyworld.com. Discount: AP/DVC save $30.', '$155–$179 + tax', 167.0, '{"festival":"After Hours – EPCOT","start":"01-22","end":"09-24","ticket_required":true}'::jsonb, ARRAY['Year-Round']::text[]),
  ('ev-disney-h2o-glow-after-hours', 'Disney H2O Glow After Hours', 'TL', 'event', 'Separately ticketed after-hours event at Disney''s Typhoon Lagoon water park with neon glow lighting and DJ atmosphere after the park closes to day guests. Includes free ice cream, popcorn, and select beverages. All slides and attractions available. A relaxed way to enjoy a water park without daytime heat and peak crowds — popular with teens and adults. Note: Select nights — verify dates at disneyworld.com. Discount: Check disneyworld.com for discounts.', '$TBD (est. $65–$85 + tax)', 75.0, '{"festival":"H2O Glow After Hours","start":"06-02","end":"09-05","ticket_required":true}'::jsonb, ARRAY['Year-Round']::text[]),
  ('ev-epcot-international-festival-of-the-arts', 'EPCOT International Festival of the Arts', 'EPCOT', 'event', 'EPCOT''s winter festival celebrating visual arts, culinary arts, and performing arts. Features Food Studios with artistically presented dishes (~$4–$12 each), the Disney on Broadway Concert Series, street art installations, live painting demonstrations, and special merchandise. One of EPCOT''s most visually striking events with typically lower crowds than Food & Wine. Note: Runs daily during festival dates.', 'Included with admission (food sold separately)', 0, '{"festival":"Festival of the Arts","start":"01-16","end":"02-23","ticket_required":false}'::jsonb, ARRAY['Season']::text[]),
  ('ev-epcot-international-flower-and-garden-festival', 'EPCOT International Flower & Garden Festival', 'EPCOT', 'event', 'EPCOT''s spring festival with elaborate Disney character topiaries, outdoor kitchen food booths (~$4–$12 each), butterfly gardens, and garden-themed entertainment. The Eat to the Beat Concert Series runs during select periods. One of the most visually beautiful times to visit EPCOT — topiary displays throughout World Showcase are a highlight. Note: Runs daily during festival dates.', 'Included with admission (food sold separately)', 0, '{"festival":"Flower & Garden","start":"03-04","end":"06-01","ticket_required":false}'::jsonb, ARRAY['Season']::text[]),
  ('ev-epcot-international-food-and-wine-festival', 'EPCOT International Food & Wine Festival', 'EPCOT', 'event', 'EPCOT''s flagship culinary festival — 30th anniversary in 2026. Features 30+ Global Marketplace food and drink booths, the Eat to the Beat Concert Series, Emile''s Fromage Montage cheese passport activity, special merchandise, and cooking demonstrations. Individual booth items typically $5–$12. Festival included with park admission; runs daily for nearly 3 months. Note: Runs daily during festival dates.', 'Included with admission (food sold separately)', 0, '{"festival":"Food & Wine","start":"08-27","end":"11-21","ticket_required":false}'::jsonb, ARRAY['Season']::text[]),
  ('ev-epcot-international-festival-of-the-holidays', 'EPCOT International Festival of the Holidays', 'EPCOT', 'event', 'EPCOT''s winter holiday festival celebrating seasonal traditions from around the world. Features Holiday Kitchens with festive food from multiple countries, the Candlelight Processional (celebrity narrator, live orchestra and mass choir — free with admission, Dining Package available for guaranteed seating), and special holiday entertainment at each pavilion. One of the most atmospheric times to visit EPCOT. Note: Runs daily during festival dates.', 'Included with admission (food sold separately)', 0, '{"festival":"Festival of the Holidays","start":"11-27","end":"12-30","ticket_required":false}'::jsonb, ARRAY['Season']::text[]),
  ('ev-rundisney-walt-disney-world-marathon-weekend', 'runDisney Walt Disney World Marathon Weekend', 'All parks', 'event', 'Walt Disney World''s flagship running weekend with races through all four theme parks. Includes 5K, 10K, half marathon, full marathon, and Dopey Challenge (all four distances). Disney-themed finisher medals and course entertainment throughout. Tickets sell out months in advance. Non-running spectators need park admission to cheer from inside the parks. Note: 4-day event: 5K, 10K, Half Marathon, Full Marathon, Dopey Challenge.', '$TBD (varies by race distance)', null, '{"festival":"Marathon Weekend","start":"01-08","end":"01-11","ticket_required":true}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ev-rundisney-princess-half-marathon-weekend', 'runDisney Princess Half Marathon Weekend', 'All parks', 'event', 'A princess-themed running weekend with costumes strongly encouraged. Features 5K, 10K, and half marathon distances with a Fairy Tale Challenge option. Popular with families and first-time race participants. Highly themed to Disney princess characters throughout the course. Note: 4-day event: 5K, 10K, Half Marathon, Fairy Tale Challenge.', '$TBD (varies by distance)', null, '{"festival":"Princess Half Marathon Weekend","start":"02-19","end":"02-22","ticket_required":true}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ev-rundisney-disney-springtime-surprise-weekend', 'runDisney Disney Springtime Surprise Weekend', 'All parks', 'event', 'A spring running event timed with the EPCOT Flower & Garden Festival. Courses run through the theme parks. A good option for runners wanting a Disney race in lower-temperature spring conditions. Note: 4-day event: 5K, 10K, Half Marathon.', '$TBD (varies by distance)', null, '{"festival":"Springtime Surprise Weekend","start":"04-16","end":"04-19","ticket_required":true}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ev-rundisney-disney-wine-and-dine-half-marathon-weekend', 'runDisney Disney Wine & Dine Half Marathon Weekend', 'All parks', 'event', 'A fall running weekend timed to coincide with the EPCOT Food & Wine Festival. The half marathon finishes inside EPCOT during the festival. Features evening race start times and post-race Food & Wine Festival access. A popular choice for runners who also want a festival experience. Note: 4-day event: 5K, 10K, Half Marathon — timed with Food & Wine.', '$TBD (varies by distance)', null, '{"festival":"Wine & Dine Half Marathon Weekend","start":"10-22","end":"10-25","ticket_required":true}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ev-disneys-not-so-spooky-spectacular-fireworks-day-guests', 'Disney''s Not-So-Spooky Spectacular Fireworks (Day Guests)', 'MK', 'event', 'A Halloween-themed fireworks show included with regular park admission on evenings when MNSSHP is not in session. A nice seasonal bonus for day guests during the fall season — a scaled-down version compared to the full MNSSHP fireworks. Note: Shown on non-MNSSHP nights only.', 'Included with admission', 0, '{"festival":"Halloween Season","start":"08-07","end":"10-31","ticket_required":false}'::jsonb, ARRAY['Season']::text[]),
  ('ev-halloween-seasonal-decor-and-overlays', 'Halloween Seasonal Decor & Overlays', 'MK', 'event', 'Daytime Halloween theming across Magic Kingdom including seasonal decorations, Halloween merchandise, and seasonal food items — available to all guests with regular park admission. Not to be confused with the after-hours MNSSHP party. Note: Runs daily during Halloween season.', 'Included with admission', 0, '{"festival":"Halloween Season","start":"08-07","end":"10-31","ticket_required":false}'::jsonb, ARRAY['Season']::text[]),
  ('ev-disneys-hollywood-studios-holiday-decor-and-sunset-seasons-greetings', 'Disney''s Hollywood Studios Holiday Decor & Sunset Seasons Greetings', 'HS', 'event', 'Holiday theming and the Sunset Seasons Greetings projection show on the Tower of Terror facade — available to all guests with standard park admission on non-Jollywood Nights evenings. A free seasonal bonus during the holiday period. Note: Sunset Seasons Greetings runs nightly for all guests.', 'Included with admission', 0, '{"festival":"Holiday Season – Hollywood Studios","start":"11-07","end":"01-05","ticket_required":false}'::jsonb, ARRAY['Season']::text[]),
  ('ev-walt-disney-world-new-years-eve-celebrations', 'Walt Disney World New Year''s Eve Celebrations', 'All parks', 'event', 'Special fireworks, dance parties, and entertainment across all four parks and Disney Springs for New Year''s Eve. Included with standard park admission. Some specific dining and experience reservations encouraged. Magic Kingdom typically offers extended park hours on New Year''s Eve. Note: Single night — Dec 31 only; dining reservations encouraged.', 'Included with admission (some add-ons available)', 0, '{"festival":"New Year''s Eve","start":"12-31","end":"12-31","ticket_required":false}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ex-enchanting-extras-fireworks-dessert-party-tomorrowland-terrace', 'Enchanting Extras – Fireworks Dessert Party (Tomorrowland Terrace)', 'MK', 'experience', 'Pre-fireworks dessert party at Tomorrowland Terrace with a sweet and savory buffet — themed desserts, chocolate fondue, fresh fruit, and non-alcoholic beverages — followed by reserved viewing of the Happily Ever After fireworks from a dedicated section. One of the best ways to guarantee a prime fireworks view without fighting crowds. Note: Reservations required — book via Disney Dining at 60-day window.', '~$99/adult, ~$59/child (3–9)', 79.0, null, ARRAY['Year-Round']::text[]),
  ('ex-disneys-not-so-spooky-spectacular-dessert-party-tomorrowland-terrace', 'Disney''s Not-So-Spooky Spectacular Dessert Party – Tomorrowland Terrace', 'MK', 'experience', 'Halloween themed dessert party at Tomorrowland Terrace with reserved viewing of Disney''s Not-So-Spooky Spectacular fireworks. Requires both a MNSSHP ticket AND a dessert party reservation. A premium upgrade for MNSSHP guests wanting guaranteed prime fireworks viewing. Note: MNSSHP ticket required in addition to dessert party reservation.', '~$99/adult, ~$59/child', 79.0, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ex-disneys-not-so-spooky-spectacular-dessert-party-plaza-garden', 'Disney''s Not-So-Spooky Spectacular Dessert Party – Plaza Garden', 'MK', 'experience', 'A more affordable MNSSHP dessert party with Plaza Garden outdoor viewing — different vantage point from Tomorrowland Terrace. Same themed dessert buffet concept with reserved outdoor viewing of Not-So-Spooky Spectacular fireworks. Note: MNSSHP ticket required in addition to dessert party reservation.', '~$79/adult, ~$49/child', 64.0, '{"festival":"MNSSHP","start":"08-07","end":"10-31","ticket_required":true}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ex-minnies-wonderful-christmastime-fireworks-dessert-party', 'Minnie''s Wonderful Christmastime Fireworks Dessert Party', 'MK', 'experience', 'Christmas holiday dessert party at Tomorrowland Terrace with reserved viewing of Minnie''s Wonderful Christmastime Fireworks. Requires both a MVMCP ticket and a separate dessert party reservation. Festive buffet with holiday-themed desserts. Note: MVMCP ticket required in addition to dessert party reservation.', '~$99/adult, ~$59/child', 79.0, '{"festival":"MVMCP","start":"11-08","end":"12-22","ticket_required":true}'::jsonb, ARRAY['Select Nights']::text[]),
  ('ex-epcot-luminous-fireworks-dining-package-rose-and-crown', 'EPCOT Luminous Fireworks Dining Package – Rose & Crown', 'EPCOT', 'experience', 'Prix-fixe dining at Rose & Crown in the UK pavilion — one appetizer, one entrée, one dessert, and unlimited select beverages — followed by guaranteed reserved patio seating for Luminous: The Symphony of Us fireworks. One of the best fireworks views at EPCOT. Requires separate park admission. Note: Reservations required — book at 60-day window.', '~$92/adult, ~$41/child', 66.5, null, ARRAY['Year-Round']::text[]),
  ('ex-epcot-luminous-fireworks-dining-package-spice-road-table', 'EPCOT Luminous Fireworks Dining Package – Spice Road Table', 'EPCOT', 'experience', 'Mediterranean small plates dining package at Spice Road Table in the Morocco pavilion with covered outdoor reserved viewing of Luminous: The Symphony of Us. A more affordable alternative to the Rose & Crown package with a different lagoon angle. Requires separate park admission. Note: Reservations required — book via Disney Dining.', '~$75/adult, ~$35/child', 55.0, null, ARRAY['Year-Round']::text[]),
  ('ex-geo-82-fireworks-experience', 'GEO-82 Fireworks Experience', 'EPCOT', 'experience', 'An exclusive adults-only (21+) fireworks experience at the GEO-82 Lounge with gourmet bites, sparkling beverages, and VIP fireworks views. Higher price than other EPCOT fireworks packages. Viewing area is partially obstructed. Best for adults seeking a sophisticated, intimate fireworks experience. A regular ADR at GEO-82 during fireworks can achieve a similar result at restaurant prices. Note: Reservations required — adults only (21+).', '$TBD (est. $125–$175/person)', 150.0, null, ARRAY['Year-Round','Adults Only (21+)']::text[]),
  ('ex-epcot-candlelight-processional-dining-package', 'EPCOT Candlelight Processional Dining Package', 'EPCOT', 'experience', 'Guaranteed reserved seating for the Candlelight Processional — a celebrity narrator tells the Nativity story with a live orchestra and mass choir — bundled with dining at select EPCOT restaurants (Biergarten, Coral Reef, Garden Grill, Le Cellier, and others). Without a dining package, standby lines can be 1–3 hours. Narrators change nightly; lineup announced closer to the festival. Requires separate park admission. Note: Daily during Festival of the Holidays; specific seating times apply.', 'Varies by restaurant ($55–$110/adult)', 82.5, '{"festival":"Festival of the Holidays","start":"11-27","end":"12-30","ticket_required":false}'::jsonb, ARRAY['Season']::text[]),
  ('ex-magic-kingdom-epcot-fireworks-cruise', 'Magic Kingdom / EPCOT Fireworks Cruise', 'All parks', 'experience', 'Private fireworks viewing from a pontoon boat on the Seven Seas Lagoon (Magic Kingdom) or World Showcase Lagoon (EPCOT). Holds up to 10 guests — excellent value when split among a group. Specialty food and beverages available to pre-order. One of the most romantic and memorable ways to experience Disney fireworks. Price is per boat. Note: Reservations required — priced per boat, not per person.', '$399–$699 per boat (up to 10 guests)', 549.0, null, ARRAY['Year-Round','Per Group']::text[]),
  ('ex-vip-tour-private-theme-park-experience', 'VIP Tour – Private Theme Park Experience', 'All parks', 'experience', 'A private guided experience with a Disney VIP Tour Guide. Includes expedited attraction access, personalized itinerary, transportation between parks, and exclusive accommodations. Park admission required separately. Price covers the guide for the whole group — best value when split among a larger family. The most seamless way to experience multiple parks in one day. Note: Book at least 60 days in advance — priced per guide hour, not per person. Discount: AP discounts may apply.', '$425–$900+/hour (min 7 hrs, up to 10 guests)', 662.5, null, ARRAY['Year-Round','Per Group','Per Hour']::text[]),
  ('ex-wild-africa-trek', 'Wild Africa Trek', 'AK', 'experience', 'An immersive 3-hour guided walk through backstage Kilimanjaro Safaris, including rope bridges over hippo and crocodile pools, a private safari overlook, and a catered snack break with savanna views. Maximum 12 guests. One of the most unique experiences at Walt Disney World — particularly memorable for nature and adventure enthusiasts. Requires park admission. Note: Multiple departures daily — book well in advance.', '$189–$249/person', 219.0, null, ARRAY['Year-Round']::text[]),
  ('ex-backstage-magic-tour', 'Backstage Magic Tour', 'All parks', 'experience', 'A 7-hour guided tour visiting backstage areas of Magic Kingdom (including the underground utilidors), EPCOT, and Hollywood Studios, with a catered lunch. A must for Disney history enthusiasts and superfans wanting a behind-the-scenes look at park operations. Requires park admission. Departs from EPCOT. Note: Select days only — verify schedule at disneyworld.com.', '~$275/person', 275.0, null, ARRAY['Year-Round']::text[]),
  ('ex-keys-to-the-kingdom-tour', 'Keys to the Kingdom Tour', 'MK', 'experience', 'A 5-hour walking tour of Magic Kingdom including a visit to the underground utilidor tunnel system beneath the park. One of Disney''s most popular guided tours for guests who want a deeper understanding of park history and Imagineering. Minimum age 16. Requires park admission. Note: Select days — verify schedule at disneyworld.com; minimum age 16.', '~$109/person', 109.0, null, ARRAY['Year-Round']::text[]),
  ('ex-disneys-family-magic-tour', 'Disney''s Family Magic Tour', 'MK', 'experience', 'A 2-hour interactive scavenger hunt-style guided tour of Magic Kingdom designed for families with young children. Ends with a special character meet-and-greet. One of Disney''s most affordable guided tour options and a great low-key addition to a park morning. Requires park admission. Note: Select mornings — verify schedule at disneyworld.com.', '~$39/person', 39.0, null, ARRAY['Year-Round']::text[]),
  ('ex-bibbidi-bobbidi-boutique', 'Bibbidi Bobbidi Boutique', 'MK', 'experience', 'A magical hair, makeup, and costume transformation experience for children ages 3–12 at Cinderella Castle. Fairy godmother-in-training packages range from the Courtyard ($99, hair and accessories) to the Castle ($450+, full gown and photo package). Also available at Disney Springs. One of the most memorable experiences for young Disney fans. Also available at Disney Springs location. Note: Available daily — book at the 60-day window; sells out fast.', '$99–$450+ depending on package', 274.5, null, ARRAY['Year-Round']::text[]),
  ('ex-savis-workshop-handbuilt-lightsabers', 'Savi''s Workshop – Handbuilt Lightsabers', 'HS', 'experience', 'A theatrical 20-minute experience to build a custom lightsaber in Galaxy''s Edge. Choose from four themes (Peace and Justice, Power and Control, Elemental Nature, Protection and Defense) which determines the hilt and kyber crystal color. The most sought-after reservation in Galaxy''s Edge. Requires park admission. Note: Reservations required — book at 60-day window; sells out fast.', '$299.99/lightsaber', 299.99, null, ARRAY['Year-Round']::text[]),
  ('ex-star-wars-droid-depot', 'Star Wars: Droid Depot', 'HS', 'experience', 'Build your own custom R-series or BB-series astromech droid at Droid Depot in Galaxy''s Edge. Droids interact with elements throughout the land. Reservations recommended but walk-ups sometimes available. A popular experience for Star Wars fans of all ages. Requires park admission. Note: Walk-up or reservation available; waits likely on busy days.', '$119.99/droid', 119.99, null, ARRAY['Year-Round']::text[]),
  ('ex-disneys-hoop-dee-doo-musical-revue', 'Disney''s Hoop-Dee-Doo Musical Revue', 'FW', 'experience', 'Walt Disney World''s longest-running dinner show — all-you-care-to-enjoy BBQ (fried chicken, smoked ribs, corn, beans, strawberry shortcake) with a live country-comedy stage show. Includes non-alcoholic beverages; beer, wine, and sangria available. Two dining plan TS credits. Consistently books out — reserve at the 60-day window. One of the most beloved experiences at Walt Disney World. Note: 3 shows nightly (5:15 PM, 7:30 PM, 9:30 PM) — book at 60-day window.', '$75–$85/adult, $47/child (3–9)', 80.0, null, ARRAY['Year-Round']::text[]),
  ('ex-spirit-of-aloha-dinner-show', 'Spirit of Aloha Dinner Show', 'POLY', 'experience', 'A Polynesian-style luau dinner show on the shores of the Seven Seas Lagoon at the Polynesian Resort. Polynesian song and dance, fire knife dancers, and an all-you-care-to-enjoy dinner with tropical dishes and signature cocktails. A beloved resort tradition — particularly memorable for families staying on the monorail loop. Note: Shows at 5:15 PM and 8:00 PM — book in advance.', '~$79–$119/adult (varies by seating category)', 99.0, null, ARRAY['Year-Round']::text[])
on conflict (id) do update set name=excluded.name, park=excluded.park, category=excluded.category, description=excluded.description, price_label=excluded.price_label, price_mid=excluded.price_mid, seasonal=excluded.seasonal, tags=excluded.tags;
